### ISSUE TITLE
The upgraded v2 examples, doest not work on your site.

### ISSUE THREAD

**Issue by pentium10** [nyroDev/nyroModal#10]
You have a syntax error somewhere as the examples does not work.

Also can you please post a link to the old version you had? with the documentation related to the old version?

**Comment by nyroDev** [comment]
Is it the same error than issue 5 reflected ?
If not, could you paste me the error here please?
And if so, I'm currently investigating on it. It looks like it only occurs on FF on Linux.

**Comment by pentium10** [comment]
I am on Windows and doesn't work neither in Chrome nor in Firefox.

I get

jquery.nyroModal.custom.js:1121 Uncaught SyntaxError: Unexpected token .
nyromodal.nyrodev.com:19 Uncaught TypeError: Object #<an Object> has no method 'nyroModal'

**Comment by nyroDev** [comment]
I updated the script. Could you clear tour cache and try again please?

**Comment by pentium10** [comment]
Ok cool it works now.

As I remember were some examples of validForm and similar stuff, I can't find them now. Where are they?

**Comment by nyroDev** [comment]
The validForm sample is still here, just under the "manual call calling through an other link"

**Comment by nyroDev** [comment]
BTW, here is the old documentation page: http://nyromodal.nyrodev.com/old/
