### ISSUE TITLE
NyroModal not working in IE

### ISSUE THREAD

**Issue by nlvraghavendra** [nyroDev/nyroModal#101]
I've created a simple html file which is actually a sample in one of your demos. It is not working in IE 8, IE 9 (I did not test any other versions). But it is working in FF 4.0, Chrome.

Here is the link to download the files - http://www.mediafire.com/?kltns1hfqj5583f

Any ideas?

**Comment by nyroDev** [comment]
Add a Doctype at the very first line of your HTML file and it should work.
