### ISSUE TITLE
Simple form validation on nyromodal

### ISSUE THREAD

**Issue by stfr** [nyroDev/nyroModal#102]
Submit validation in nyromodal seems to ignore home-made submit() event declaration :

You can try it here :

http://stephanerouille.fr/labs/experiments/nyromodalv2/

**Comment by nyroDev** [comment]
As shown in the nyroModal home page, form valdiation should be done on your duty, and then, when the form is valid, you should bind nyroModal and call it with:
validForm.nyroModal().nmCall();
