### ISSUE TITLE
iframes height

### ISSUE THREAD

**Issue by cancunjc** [nyroDev/nyroModal#103]
Hi, 

I have in my page 2 buttons, each one opens an IFrame... the first IFrame must have a 330px height and the second 660px... I'm setting minH, h, initH, but they are not working...  the height always is the one declared at:

 .nyroModalCont iframe {
    width:100%;
    height: 530px;
    overflow: hidden;
}

but I need diferent height in the same page... so, changing default css at  .nyroModalCont iframe {}  is not a solution  :(

Please help

**Comment by mindbodyheart09** [comment]
I'd like to dynamically adjust iFrame dimentions too.

**Comment by cancunjc** [comment]
hi mindbodyheart,  I solved it adding:  
.nyroModalIframe{
    height: 100%;
}

now this works:
        $(function() {
                $('.btnBuscar').nyroModal({
                    modal: true,
                    sizes: { minW: 860,  initH: 530,  minH: 530, h: 530 }
                });
                $('.btnImagen').nyroModal({
                    modal: true,
                    sizes: { minW: 360, initH: 330,  minH: 330, h: 330  }
                });

```
     });
```

**Comment by vishalmelmatti** [comment]
Hi,

I could manage to achieve the different sizes of nyroModals by following below procedure. This may not be the best way to do it but it worked for me ..

Changing the width of iframe from CSS to 100%

<style>
.nyroModalCont iframe {
    width:100%;
    height: 530px;
    overflow: hidden;
}
</style>


and then passing different size options to modal window initialization ..

```
$('.nm1').nm({
    sizes: {
        minH: 500,
        minW: 650
    }
});

   $('.nm2').nm({
    sizes: {
        minH: 500,
        minW: 1050
    }
   });
```

**Comment by nyroDev** [comment]
This is actually the best way to do it through nyroModal.
