### ISSUE TITLE
The container is not resized (width or height is 0) in Chrome

### ISSUE THREAD

**Issue by andreyshipilov** [nyroDev/nyroModal#104]
I don't really get it, but isn't there anyone here who have tested it in Chrome? Even the examples on the website do not work.

Check it yourself in any Chrome version. http://nyromodal.nyrodev.com/#demos

Gallery Img 1 — first click
http://gyazo.com/9d6da5a8b1364f25fbc445ccad0c812b.png

Gallery Img 1 — second click
http://gyazo.com/d1ac0c0a0dea9a2d92f1efac2bb7b911.png

**Comment by dcbell** [comment]
I am using the following code and it works partially (the size isn't 0, but at the moment I can't resize it):

```
$.nmManual('prompt.html', {
    //modal removes the ability to exit via the 'esc' key or clicking outside the window'
    modal: true,
    sizes: {
        w: 800,
        h: 200
    },
    callbacks: {
        //set focus to the first textbox in the modal window
        afterShowCont: function(elt, settings) {
            $('input:text:first', elt.content).focus();
        }
    }
});
```

FYI, I am running Chrome 12.0.742.122

**Comment by xsalto-camille** [comment]
Hello,
I have the same bug with Chrome on Ubuntu (not with other browsers and not with Chrome on Windows) when I try to display an image for the second time with the default code :
<code>$('.nyroModal').nyroModal()</code>
For example, when I click on a nyroModal link the image appear with her correct dimensions 800x600, and next I close the lightbox and click a second time on the same link : the box container has a size like 0x0 :
<code>position: fixed; width: 0px; height: 0px; top: 178.5px; left: 683.5px; overflow-x: auto; overflow-y: auto;</code>
and my image has too the same dimensions :
<code>&lt;img src="image.jpg" width="0" height="0"&gt;</code>
I have the same bug when I display an image for the second time in a diaporama (with arrows back/next).

I am running Chrome  11.0.696.68

**Comment by andreyshipilov** [comment]
Looks like the developers just don't test it under Chrome...

**Comment by nyroDev** [comment]
This bug seems to not exist anymore on Chrome.
