### ISSUE TITLE
nmObj not working?

### ISSUE THREAD

**Issue by got3nks** [nyroDev/nyroModal#105]
This is my javascript.

$(document).ready(function() {  
    $('.nyroModal').nyroModal();

```
$.nmObj({
    callbacks : {
        afterClose: function(nm) {
            alert("closed"); }
        }
});
```

});

The alert is never shown. I know I can set the callback in the first call $('.nyroModal').nyroModal() but I want to understand how to use the $.nmObj function.

Thank you.

**Comment by nyroDev** [comment]
Try to use the nmObj function BEFORE using the nyroModal.

**Comment by got3nks** [comment]
Isn't there any way to specify callbacks later then inizializing with .nyroModal()? I want to change callbacks on the fly, that's why I'm asking..

**Comment by nyroDev** [comment]
The nmObject is stored using the data function with the name of 'nmObj'.

Therfore, you could use something like:

<pre>$('.nyroModal').data('nmObj', $.extend(true, {callbacks:{}}, $('.nyroModal').data('nmObj'));</pre>

**Comment by nyroDev** [comment]
My bad. Be sure to change the nmObj element by element, using a each loop, like:

<pre>
$('.nyroModal').each(function() {
  var me = $(this);
  me.data('nmObj', $.extend(true, {callbacks:{}}, me.data('nmObj'));
});
</pre>

**Comment by got3nks** [comment]
Unfortunately I can't understand what you said. But I found that this seems to do the job:

<pre>
function loggedIn() { // function called on successful login
    $.nmTop().callbacks =  {
        afterClose: function(nm) {
            top.window.location.href = top.window.location; // refresh the page
        }
    };
    $.nmTop().close();
}
</pre>

**Comment by nyroDev** [comment]
$.nmTop() retrieves the nmObject only for the currently shown nyroModal.
My solution will update callbacsk for every nyroModal binded elements, which are or are not shown at the moment.

**Comment by got3nks** [comment]
Oh I just read your 2nd comment, that makes sense. How can I change the settings for the current modal only though? (My solution may not be good in style but it seems to work)

**Comment by nyroDev** [comment]
If you want to change only the currently modal shown, then using $.nmTop() is the only good way to do it.
Your code is right.
