### ISSUE TITLE
Minified version not working in IE7 & IE8

### ISSUE THREAD

**Issue by wietsewarendorff** [nyroDev/nyroModal#106]
Hi there,

I'm using this script for a while now, works great! But today I ran into a problem in IE8, and after some testing I found that the minified version in the download (jquery.nyroModal/js/jquery.nyroModal.custom.min.js) results in a jQuery error: "exception thrown and not caught". When I replace the minified version with the normal version (jquery.nyroModal/js/jquery.nyroModal.custom.js), it's working as it should. In IE9 (even with compatibility mode on), FF & Chrome the minified version is fine, but IE7 produces the same problem as IE8.

For now, I just replaced the minified version with the "normal" version. Any idea why this is happening, and if there is a solution for this problem?

**Comment by nyroDev** [comment]
This issue seems to be fixed now.
