### ISSUE TITLE
Add content to the loading modal

### ISSUE THREAD

**Issue by got3nks** [nyroDev/nyroModal#107]
I would like to add a link "Click here if the loading stucks" in the loading div because I found out that sometimes the AJAX loading stucks (it does not return any error but from Firebug I can see the page is not load at all, no bytes received from the server) and it won't time out either. What's the easiest way to do so?

**Comment by got3nks** [comment]
I added 

$(nm.elts.load).html("text");

to the function initElts, it seems to do the job. :) If you have any better solution, lemme know.

**Comment by nyroDev** [comment]
What you could do is add a callbacks (with callbacks setting or via a filter) for the beforeShowLoad function and do exaclty what you did on your previous comment.
