### ISSUE TITLE
iframe login form and post back to page across domains

### ISSUE THREAD

**Issue by WebPhenom** [nyroDev/nyroModal#108]
We have a page that links to a separate login form through an iframe modal. Upon submitting the form in the iframe, the form posts data back to another page and closes the modal. So when the modal iframe submits, the modal should disappear and the parent window will show the data from the post in a new page. Can't seem to get the page to show the posted data though.  The two pages are on different servers and the post works if there is no modal , straight HTML. But with the modal code in place the post does not work. Is what we are trying to do possible?

**Comment by nyroDev** [comment]
To do that, you can simply make your form submit content directly in the page, without adding the nyroModal class.
On the posted page, you could show an other modal with the confiramtion message.
