### ISSUE TITLE
disabling iframe refresh on enter key hit, when modal is opened.

### ISSUE THREAD

**Issue by gnrlbzik** [nyroDev/nyroModal#110]
I need to disable iframe refresh, when i hit enter key when modal is opened, not sure how to go about it. There is no clear documentation on that. Thanks.

**Comment by nyroDev** [comment]
I'm not sure what you mean with "disable iframe reflesh on enter key hit", but what you could do is using a callback (afterShowCont for instance) and bind the document keyPress event, detect if it's the enter key, and prevent the event in this case.
