### ISSUE TITLE
nyromodal form and wysiwyg submission via ajax

### ISSUE THREAD

**Issue by jean-paul** [nyroDev/nyroModal#111]
This is less of a bug fix as more of a how to but I wasn't sure where else to post it.

If you're using a wysiwyg editor such as ckEditor in a nyromodal then you may find that the HTML created in the editor isn't present when submitting.

The answer to this is to update the textarea form element with the contents of the editor at the initElts callback

here is an example with ckEditor in mind using jquery

// force ckeditor to update textarea
        function updateEditor(id){

```
        // get instance cache to var
        var instance = CKEDITOR.instances[id];

        instance.updateElement();
    }
```

function update_ckeditor(){

```
        if(typeof(CKEDITOR) != 'undefined' && $('.ckeditor textarea').length > 0){
            $('.ckeditor.basic textarea, ckeditor.full textarea, .ckeditor.custom textarea').each(function(){
                id = $(this).attr('id');    
                updateEditor(id);
            });
        }

    }
```

$.nmManual(url,{
            callbacks:{
                initElts:function(){

```
                // update ckeditor element
                update_ckeditor();
            }
        }
```

});

**Comment by nyroDev** [comment]
Thanks for sharing!
