### ISSUE TITLE
Having trouble with nyroModal Size Options

### ISSUE THREAD

**Issue by dcbell** [nyroDev/nyroModal#112]
I am trying to get a nyroModal popup with a fixed size. I have tried the following:

```
$.nmManual('message.html', {
  modal: true,
  w: 400,
  h: 200
});
```

and also

```
$.nmManual('message.html', {
  modal: true,
  sizes: {
      w: 400,
      h: 200
  }
});
```

to no avail. The window will not reflect the sizes I selected. Please help!

**Comment by jimolina** [comment]
Hi

For my, the solution was:

jQuery(".nyroModalCont").css({
     "width": "500px"
});

**Comment by nyroDev** [comment]
Try to set the minW and minH also on the sizes setting.
Be sure to check the default CSS to set minimum size too.
