### ISSUE TITLE
$.nmManual embeded in another 

### ISSUE THREAD

**Issue by 9jaGuy** [nyroDev/nyroModal#113]
I two links
Log In =         $.nmManual("#modal_login");
Register =         $.nmManual("#modal_register");

the login modal has a link  to "Register", when i click register from the login modal, it removes the first "login" modal from the DOM, so next time you want to open the logi modal, nothing comes up because it cannot be found.

A temp fix that i used it to 
call $.nmTop().close(); before  $.nmManual("#modal_register"); but the transition is not smooth

**Comment by nyroDev** [comment]
I tested it with a simple pahe, and it seems to work now.
