### ISSUE TITLE
nyroModal and form : how to close if OK

### ISSUE THREAD

**Issue by Bacteries** [nyroDev/nyroModal#115]
Hi,
I use nyroModal on some project and I really love this library so thanks to NyroDev for it!

I would like to have a behaviour like this :
- User click on a link that open a nyroModal with a form inside it
- I attach a nyromodal to the form
  
   $('#myModalForm').nyroModal().nmCall();
- All work fine : when I submit my form I have my form result in the modal.
- Now I would like to show the content if there is a problem (like an error) and do an action based if all was OK. For this I need to get the response of my form submit.
  How can I achieve this?

I would like to test if the form submit return json, if yes : do the valid case, if not display the content in the modal.

I try something like this :

```
 $('#myModalForm').nyroModal({
        callbacks:{
            init: function(nm) {
                alert('OK');
            },
            initElts:function(nm){
                alert('OK2');
            }
        }
    }).nmCall();
```

But I don't see where I can access the response. 

Any idea?

Thanks!

**Comment by Bacteries** [comment]
Humm, i check for filters, but I don't really see how to use it. Is there any example for this?

**Comment by nyroDev** [comment]
What I would suggest is simple bind the form not with nyroModal, but with your own function.
Handle by yourself the form submit, and do your check regarding the result.
Then, depending on what you get, do what you need using nyroModal functions or others stuffs.
