### ISSUE TITLE
Wiki not working

### ISSUE THREAD

**Issue by carloand** [nyroDev/nyroModal#117]
Hello,
  the nyromodal wiki at http://nyromodal.nyrodev.com/wiki/index.php/Main_Page looks hacked and the contents are gone! 
Could you have a look? Thank you in advance!

Carlo.

**Comment by rphki** [comment]
I fixed it – seems to happen quite frequently :-/

**Comment by carloand** [comment]
Hello,
  the nyromodal wiki is gone again. Could you re-enable it? It was very useful. Thank you;

Carlo.

**Comment by nyroDev** [comment]
I disabled it as it was hacked pretty often.
You may use the wiki feature of Githu, isn't it?
