### ISSUE TITLE
IE8 - Position absoulte Not Working

### ISSUE THREAD

**Issue by Strikingknife** [nyroDev/nyroModal#12]
Hi Guys, I am using the NyroModal for the popup window, the popup window in IE8 does not scroll when u scroll the page. But in mozilla thats not the case.

It will be great, if someone could help me with this

**Comment by nyroDev** [comment]
Everything looks fine on my IE8.
Did you correctly add the CSS?

**Comment by Strikingknife** [comment]
I m using nyromodalfull.css, is there any specific doc type required? Bcos the same code works fine in mozilla.

**Comment by nyroDev** [comment]
You have to set a doctype. Transitionnal or strict should be OK.
Note that for IE, the Doctype has to be set at the very top line of the HTML, without any space at the beginning.
