### ISSUE TITLE
Remove hardcoded opacity for element "bg" should be removed

### ISSUE THREAD

**Issue by ADmad** [nyroDev/nyroModal#120]
The hardcoded value opacity value 0.7  for overlay element "bg" [here](https://github.com/nyroDev/nyroModal/blob/master/js/jquery.nyroModal.js#L734)  and in other filters overrides the value of opacity you set in the class for #nyroModalBg. So the hardcoded values should be removed and just css values applied.

**Comment by rphki** [comment]
If I get it right, setting it in the filters and not only via global CSS could provide more flexibility – _if_ it is possible to set the opacity _per link_ (see https://github.com/nyroDev/nyroModal/issues/122). But of course the default filters could simply use the CSS value, which would cause a less astonishing behaviour ;-).

**Comment by vishalmelmatti** [comment]
Hello Friends,

Can anybody please help me to reduce the opacity value  ? 

$('.nyroModal').nm();

How to pass options to this? I tried but does not work .

Thanks

**Comment by nyroDev** [comment]
If you want to change the opacity hardcoded in the fade anims filter, simply do something like:

``` javascript
$.nmAnims({
    fade: {
        showBg: function(nm, clb) {
            nm.elts.bg.fadeTo(250, 0.7, clb);
        }
    }
});
```

Change the 0.7 value to the opacity you want.
