### ISSUE TITLE
fixed header and footer with scrollable content

### ISSUE THREAD

**Issue by azpublic** [nyroDev/nyroModal#121]
Hi, 

I've been reading this issue 

https://github.com/nyroDev/nyroModal/issues/13

and I'm trying to achieve this effect 

http://i52.tinypic.com/a47st3.png 

without success.
 My problem is that the title scrolls with the entire wrapper div ... 
could you help me figure out how this could be done please ? 

I think the problem lies in the fact that overflow:auto is systematically added  / hardcoded to  #nyroModalCont  

Thanks for helping

**Comment by nyroDev** [comment]
To do these kind of things, you will have to : 
1. Add position relative to nyroModalCont
2. Position absolute your header and footer
3. add margin top and bottom to your nyroModalNNN (wher NNN is corresponding to your type of filter used to load the content, like Link)
