### ISSUE TITLE
Overwriting showBg animation (e.g. opacity) per link

### ISSUE THREAD

**Issue by rphki** [nyroDev/nyroModal#122]
Is there a way to change the showBg animation per link? This would be nice for stacked modals to avoid seeing darker and darker backgrounds...

The Wiki shows only a way to do this globally (http://nyromodal.nyrodev.com/wiki/index.php/Change_the_background_opacity). I tried to do 

```
$('.myLink').nyroModal({
    anim: {
        showBg: showBgLight
    }
});

function showBgLight(nm, clb) {
    nm.elts.bg.fadeTo(250, 0.1, clb);
}
```

but it doesn't work - the function showBgLight is actually checked for existence (throwing an error if rename it), but never called. The anim _is_ overwritten though, i.e. the default behaviour is disabled, but instead of calling my function the "basic" variant is used. Because of this "fallback" behaviour I wonder if it actually _should_ work the way I tried and just fails due to some bug.

PS: If I define my custom anim function directly in the nyroModal call's param, the effect is just the same.
PPS: This is somehow related to https://github.com/nyroDev/nyroModal/issues/120

**Comment by nyroDev** [comment]
Feature add in commit 35ad2079c275a2bc2d05fd68d697b2893fc36a3e
