### ISSUE TITLE
how to stop nyroModal reposition

### ISSUE THREAD

**Issue by ghost** [nyroDev/nyroModal#124]
Hi all

I am implementing the nyromodal to a page which consists of facebook comment plugin.
The nyromodal window has a fixed top margin 180px and it works well most of the time, I mean the popup position.

However, if I open the nyromoal before the facebook comment plugin is ready, the nyromodal library will automatically change the top value of .nyromodalCont div from 0 to some value.

So, my question is, is there any way to stop nyromodal library script to do reposition on the nyromodal window?

**Comment by nyroDev** [comment]
If you mean disable the resizing of the modal when the window is resized, you can do it by calling:

``` javascript
$(window).off('resize');
```

You only need to do it once after the first nyroModal init.
