### ISSUE TITLE
nyroModal with header and footer

### ISSUE THREAD

**Issue by taimar** [nyroDev/nyroModal#13]
Hi.

Currently nyroModal supports one so-called content section which gets scrollbar when its content is very long. I often need to implement modal windows with header and footer so that they are always visible and only the content section scrolls if necessary (if content is longer than viewport height minus header height minus footer height).

It would be really helpful if we could use a native 3 section template (fixed-height header, dynamic content and fixed-height footer) and custom HTML in all 3 sections.

What do you think of it?

**Comment by nyroDev** [comment]
It could be a good idea.
I'm pretty sure we can do that with a simple filter.
Basically you need to append and prepend some HTML values inside the content, right?

**Comment by taimar** [comment]
I’m not sure what do you mean by “need to append and prepend some HTML values inside the content”.

I think nyroModal could have following options (false and null by default):

```
nyroHeader: true,
nyroHeaderContent: '<h1>Title</h1> <p><a class="nyroModalClose" href="#">Close</a></p>',
nyroFooter: true,
nyroFooterContent: '<p class="action"><input type="submit" value="Save"> <input type="reset" value="Cancel"></p>'
```

…and/or:

```
nyroHeader: true,
nyroHeaderElement: '#modalwin1-header',
nyroFooter: true,
nyroFooterElement: '#modalwin1-footer'
```

…and/or:

```
nyroHeader: true,
nyroHeaderElement: this.find('.modal-header:eq(0)'),
nyroFooter: true,
nyroFooterElement: this.find('.modal-footer:eq(0)')
```

It would be great if we can enable/disable header and footer separately as show above.

Does it make sense?

**Comment by nyroDev** [comment]
Yes it makes sense.
As I said, this won't be included in the core. Instead, I'll do it in a filter so only person who need this feature will download and incldue it.

**Comment by taimar** [comment]
Great!

By the way, I think the logic behind second and third example is the best because:
1. Developers can define header and footer elements by any jQuery selector and automatically for all similar nyroModal instances.
2. All the HTML markup can be located in one place.

**Comment by nyroDev** [comment]
The developper will have to provide a HTML string OR a DOM element or anything he want. He will have to care about where it comes from.
I'll simply use the content of it with the function append and preprend on the content of the modal, just after the orgiinal content has been inserted.

**Comment by taimar** [comment]
Sounds good. I’m eager to try out. :)

**Comment by nyroDev** [comment]
Add imageRegex parameter in nmObject and use it in image filter. #Closed by 8f2a6a44afda25bf8f98d6d577b293f4ea0e02f2
Fix CSS error. Closed by 8f2a6a44afda25bf8f98d6d577b293f4ea0e02f2
Add header and footer parameter in nmObject. Closed by 8f2a6a44afda25bf8f98d6d577b293f4ea0e02f2

**Comment by taimar** [comment]
Could you provide a demo on your site with header and footer enabled? I'm not sure it works in a way I intended it to work.

I'm getting this result (the whole nyromodal scrolls, footer is hidden):
http://i56.tinypic.com/2qbua8h.png

...but the desirable result is this one (only the content scrolls, header and footer are always visible): http://i52.tinypic.com/a47st3.png

Thanks.

**Comment by nyroDev** [comment]
@Tainmar, you have to do so using CSS.
I don't have time for now to explain that, but use position absolute and relative might do the trick.
