### ISSUE TITLE
Example html files and will it display a pdf

### ISSUE THREAD

**Issue by jrlanders** [nyroDev/nyroModal#130]
Hi Nyro,
I cannot get to your home site for some reason.  Do you have some example html files I can look at.  The core of what I am trying to do is to display a PDF file in a modal window.  Will nyroModal do that?

Regards
James

**Comment by nyroDev** [comment]
In order to show a PDF inside a modal, you'll have to show it in a iframe.
To do so, simply create your link with target=_blank to your PDF, call nyroModal() function on it and it should work.
