### ISSUE TITLE
Can't Add SWF-Playing-video to a gallery

### ISSUE THREAD

**Issue by ghost** [nyroDev/nyroModal#131]
Hi!

I'm trying to make a modal gallery with 9 objects (8 images and 1 SWF playing a FLV video).

Playing the video in a single modal (without gallerying) works perfect.
But when i try to include it in a galery (rel="gallery2") it doesnt work (not even takes the size parameters).

```
$(function() {
    $('#video').nyroModal({
        sizes: {
            w: 640, 
            h: 400,
        },
        swf: {
            FlashVars: 'file=flv_video.flv&autostart=true' 
        }
});
});

<a href="../path/to/player.swf" id="video" title="Video" ref="gallery1"><img src="../path/to/gallery.jpg"></a>
```

Anyone know i can get the video playing inside the gallery? (i dont want to embed a youtube video if you are thinking advising me that solution :P)

Many thanks in advance !!!

**Comment by nyroDev** [comment]
Could you post a link or a page where we can see it in action?
