### ISSUE TITLE
nyroModal with video player

### ISSUE THREAD

**Issue by Grihal** [nyroDev/nyroModal#132]
Hello everyone,

I try to insert a video player in my nyroModal.
It works on Firefox and Chrome but not on IE...

You can see an example here : http://www.galae.info/52-16830-test-nyromodal.php

In IE the player don't appear but you can see is location.

Anyone can help me ?

Thank you.

**Comment by Grihal** [comment]
Up!

**Comment by nyroDev** [comment]
Did you try by adding the wmode transparent or by removing the float right?
