### ISSUE TITLE
Blank window in nyro with IE7-8 ?

### ISSUE THREAD

**Issue by romaindudek** [nyroDev/nyroModal#133]
Hi,

I'm having troubles with my contact form opening in nyroModal ajax request...
Under Chrome, FF, Safari : No pb.

Under IE... Nothing shows up, a nyromodal window opens, but nothing in it and no error message...

When I try it with an image, it works... Sligthly strange...

I have the latest jQ (1.6.4) and nyroModal V 2.0.0

My mainpage : http://studioneptune.fr
(you have to click on 'contact in the lright part of the nav menu)

The adress of my contact page : http://studioneptune.fr/contacts/

Thx for helping...

**Comment by nyroDev** [comment]
Line 30 of contact page have a HTML error in the anchor element.
There is "color:#0000FF;text-align:left"" around where it shouldn't.
Try to remove it first.
