### ISSUE TITLE
resize function in niroModal v2

### ISSUE THREAD

**Issue by jca0310** [nyroDev/nyroModal#134]
Hello,

I would like automatically resize my nyroModal if there are errors in my form submission (Spry validation). I believe i must use this :

$.nmTop().resize(true);

But i don't understand how i can use it. Please help me :-)

Thanks.

**Comment by jca0310** [comment]
anyone please ?

**Comment by nyroDev** [comment]
nyroModal should resize by itself once you loading new content.
It you cant to resize the nyroModal after you added some HTML element by yourself, you should, as you mentionned, call
$.nmTop().resize(true);

After adding your content.
