### ISSUE TITLE
manualcall

### ISSUE THREAD

**Issue by bbevren** [nyroDev/nyroModal#135]
When i loaded the page it works fine, but when load new content with ajax and recall the script below Nm overlaps i cannot close the previous opened modal...

$('#download').click(function(e) {
    $.nmManual('download.php?id='+id+'');  
  });

**Comment by nyroDev** [comment]
I'm sorry, but I don't understand what is your bug.
As it's 1 year old, please reopen this issue if you want to be more clear.
