### ISSUE TITLE
href change

### ISSUE THREAD

**Issue by pjam** [nyroDev/nyroModal#136]
Hi all.

I'm having a problem that I can't solve.

I have a link that opens a nyroModal, and with some action and closing the window, the original href of the link is changed with js. The problem is that when I click the link again, what pops up in the nyroModal is the content of the original href, and not the new one. How can I fix this?

I think it can somehow be done by recalling or re-init-ing the link filter, but I don't know how to do it.

Can someone help me please?

Thanks

**Comment by nyroDev** [comment]
There was no clean way to do it.
In the following commit, I added a nmDestroy function.

Then, you'll simply do:
$('#link').nmDestroy.nyroModal();
