### ISSUE TITLE
SVG Support

### ISSUE THREAD

**Issue by charwick** [nyroDev/nyroModal#139]
Links within SVG use &lt;a xlink:href="..."&gt; syntax instead of &lt;a href="..."&gt;. NyroModal ignores this unless href attributes are added first, which is invalid SVG. Seems like it wouldn't be too much of an issue to have it recognize xlink:href attributes as well as href for opening iFrame modals.

**Comment by nyroDev** [comment]
I actually never worked with SVG.
As you said, it could be pretty simple to add support for SVG with a filter designed for it.
If you could let me know which HTML should be inserted, how we can now the size of the element end stuff like that, I could write it.
