### ISSUE TITLE
Image gallery dont show after clicked a second time

### ISSUE THREAD

**Issue by jonasboman** [nyroDev/nyroModal#140]
First time after page load the image gallery works fine.
I call the function using $("a[rel=image]").nm();

When closing the modal and clicking on one of the image links in gallery the image don't show. Next /prev image don't show either.

Using Chrome - 14.0.835.202 m  on Windows 7 Enterprise

**Comment by jonasboman** [comment]
I stand corrected; it is the width och height of the nyroModalImg div and img that does not update correctly.

**Comment by nyroDev** [comment]
Thsi bug seemes to be fixed now.
It was a cache issue.
