### ISSUE TITLE
Opera older than 11 can’t get width content of .nyroModalCont

### ISSUE THREAD

**Issue by conmute** [nyroDev/nyroModal#142]
At first time i was glad to use your plugin. But there are more to do.....
In an Opera 10.51 existing problem to get width (i think its for all version less than 11)

<pre>
/*
 * nyroModal v2.0.0
 * 
 * Image filter
 * 
 * Depends:
 * - filters.link
 * 
 * Before: filters.data
 */
// ....... here goes code before
            size: function(nm) {
// My prepended code
// this helps Opera to parse width of image, 
// But when resize() launching size of image are incorect :( maybe you can find where to fix that to
                var t = new Image();
                t.src = nm.elts.hidden.find('img').attr('src');
                nm.sizes.initW = nm.sizes.w = t.width;
// Your code
                if (nm.sizes.w != nm.sizes.initW || nm.sizes.h != nm.sizes.initH) {
                    var ratio = Math.min(nm.sizes.w/nm.sizes.initW, nm.sizes.h/nm.sizes.initH);
                    nm.sizes.w = nm.sizes.initW * ratio;
                    nm.sizes.h = nm.sizes.initH * ratio;
                }
                var img = nm.loading ? nm.elts.hidden.find('img') : nm.elts.cont.find('img');
                img.attr({
                    width: nm.sizes.w,
                    height: nm.sizes.h
                });
            },
// ....... there goes code after            
/*
 * nyroModal v2.0.0
 * 
 * Iframe filter
 * 
 * Depends:
 * - filters.link
 * 
 * Before: filters.formFile
 */
// ....... here goes code before
            load: function(nm) {
// Your code
                nm.store.iframe = $('<iframe src="javascript:\'\';" id="nyromodal-iframe-'+(new Date().getTime())+'"></iframe>');
                nm._setCont(nm.store.iframe);
// My apended code
// Opera beyond 11 still cant parse width, so i placed an static width far ALL iframes on my project...
// But its good to be variable
                nm.sizes.w = 813;
            },
// ....... there goes code after
</pre>

Sorry for my bad English, still didn’t learn it well.

**Comment by nyroDev** [comment]
Opera 11 was released on december 2010.
I won't fix this bug.
