### ISSUE TITLE
IE error when go to next slide

### ISSUE THREAD

**Issue by reinos** [nyroDev/nyroModal#146]
When I want to go to the next slide (click the cursor keys or by ($. NmTop (). _callFilters (GalleryPrev ') / $. NmTop (). _callFilters (' Gallery next');)) Give Internet Explorer a error "Invalid argument.".

When I use the development version of jQuery 1.7.1 in charge, I see that the problem at line 8826 in "fx.elem.style [fx.prop] = + fx.now fx.unit," rise.
When I put a try catch around it:

```
                try {
                    fx.elem.style[fx.prop] = fx.now + fx.unit;
                } catch (err) {
                    console.log(err, fx.now, fx.unit); 
                }
```

I get the following message: "LOG: Error: Invalid or argument.NaNpx LOG: Error: Invalid argument.autopx".
It seems to be no good values ​​in the fx.unit it.

I use. Nyro latest version: v2.0.0 and jQuery 1.7.1

**Comment by nyroDev** [comment]
The code you mentionning seems to come from jQuery itself.
Does the bug still occurs with the last version of jQuery and nyroModal?
If so, could you please send a test page link?
As this bug is 11 months ago, I will close it. Feel free to reopen it to answer it.
