### ISSUE TITLE
how to open on body load?

### ISSUE THREAD

**Issue by Gesley** [nyroDev/nyroModal#147]
how to put nyro and open on body load ?

myscript
[ ... ]

<script type="text/javascript">
$(function() {
  $('.nyroModal').nyroModal();
});
</script>

</head>

<body>

<p><a rev="modal" class="nyroModal" href="enquete.php">Ajax without closing</a></p>

<div class="nyroModal"></div>

[ ... ]

**Comment by nyroDev** [comment]
Simplye do something like : 
$(function() { $('#myLink').nyroModal().nmCall(); });
