### ISSUE TITLE
 how to change the size of nyroModal for a specific modal window?

### ISSUE THREAD

**Issue by vishalmelmatti** [nyroDev/nyroModal#148]
Hi,

.nyroModalCont iframe {

}

Changing the above class in css changes the size of all modals. I want to ask how to change the size of nyroModal for a specific modal window?

Thanks

**Comment by hector-valdivia** [comment]
Yeaa, I have the same issue, someone?

**Comment by vishalmelmatti** [comment]
Hi,

I could manage to change the size of specific modal by giving 100% width to the iframe e.g.

.nyroModalCont iframe {
    width:100%;
    height: 530px;
    overflow: hidden;
}

and then pass different minH and minW e.g. 

```
$('#nm1').nm({
    sizes: {
        minH: 500,
        minW: 1050
    }
});

$('#nm2').nm({
    sizes: {
        minH: 500,
        minW: 650
    }
});
```

**Comment by hector-valdivia** [comment]
Let's proves, thanks for the tip
