### ISSUE TITLE
BUG when click V.2 and POST "multipart/form-data"

### ISSUE THREAD

**Issue by choonoi** [nyroDev/nyroModal#15]
when use modal in modal it will open 2 windows 
example code.
[code]
&lt;form action="test.php" class="nyroModal"&gt;
name : &lt;input type="input"&gt; 
&lt;a href="check.php" class="nyroModal"&ht;check</a&gt;
&lt;input type="submit"&gt;
&lt;/form&gt;
[/code]
wheck i click on "check" it will open 2 URLs and 2 windows.
so , it should open only "check" URL

and also when i send POST data with  enctype="multipart/form-data"

it will get some error

**Comment by nyroDev** [comment]
Stop bubbling events on custom events. Closed by ecbfb31512d770b305091116d6ef3c7585471d12

**Comment by choonoi** [comment]
could u tell me how to ?

**Comment by nyroDev** [comment]
What do you mean? This bug is fixed with the commit mentionned in the comment.
Re-download nyroModal and this bug should be fixed.

**Comment by choonoi** [comment]
thank you , I will try again and let u know.
if I found other bug.

**Comment by choonoi** [comment]
seem it not fix yet.
when i upload file and target in modal. it's said "An error occured"

**Comment by choonoi** [comment]
the form upload file it on modal window and after submit it still reload in same modal.
and it say "An error occured"
