### ISSUE TITLE
modal:false not working

### ISSUE THREAD

**Issue by vishalmelmatti** [nyroDev/nyroModal#151]
Hi,

I am passing below arguments to nm modal,

nm({
        modal: false,
        sizes: {
            minH: 500,
            minW: 650
        }
    });

it takes sizes option but does not apply modal false option. Popup always opened as modal, I do not want it as a modal window. I want only popup. 

Please help.

**Comment by nyroDev** [comment]
modal fals is set by default.
The only place where modal is set to true, is when you have a rev=modal attribute set on the opener element.
So I don't understand what's happening.
If you still want to give feedback about that, feel free to reopen this issue.
