### ISSUE TITLE
IE 7 & 8 form not work properly.

### ISSUE THREAD

**Issue by sanjay-virtueinfo** [nyroDev/nyroModal#153]
Hi,
Does any one tried form in poup with vertical scrollbar. I have a strange issue in IE. 
I have a registration popup with vertical scrollbar. When I try to submit form using return key it's work fine for other browser but not for IE 7 and 8. Actually the submit button is not visible when form is load. But if I scrolldown my popup and make a submit button visible it's work fine. So please help me.

Thanks in advance.

**Comment by nyroDev** [comment]
This is known issue from IE6, 7 & 8.
When the submit button isn't visible, hitting the enter key have no action.
To fix it, bind a keypress on your field and manually submit the form using jQuery.
