### ISSUE TITLE
Problem with mobile & tablet devices

### ISSUE THREAD

**Issue by Oscar-M** [nyroDev/nyroModal#154]
Hi,
I´m trying to implement nyromodal in some websites for mobile optimization, and the problem is that the window doesn´t auto adjust in the center of the screen. It remains on top of the total height of the screen. Could you fix this problem?
Thanks in advance!

**Comment by MACscr** [comment]
Ah, that is a big problem. I hope this gets fixed as well.

**Comment by Oscar-M** [comment]
It works correctly updating to IOS5

**Comment by tejit2004** [comment]
Hi,

Could you please let me know hiw you optimized modal for mobile screens, its such a nightmate.
