### ISSUE TITLE
nyromodal and iframes 

### ISSUE THREAD

**Issue by michaelcarl** [nyroDev/nyroModal#158]
Hi,

i'm using this code in a website:

< a class="nyroModal" title="dummy" href="#test1" >
    < span>CLICK< /span >
          < div style="display: none; width: 600px;" id="test1"> 
            < iframe width="800" height="600" frameborder="5" id="test" src="http://www.dummy.com/test/dummy.html" ></iframe >
          </div> 

< script type="text/javascript">
$(function() {
  $('.nyroModal').nyroModal();
});
</script > 

this works, but the link works only once. when i click second time i see a white page in the iframe area. could anyone help me please?

thanks!!!

michael

**Comment by nyroDev** [comment]
Why don't you use the iframe feature of nyroModal?
Simply link yo your page on your link and nyroModal should do the rest.
There is many bug and wrong elements with iframes...
