### ISSUE TITLE
BUG when submit enctype="multipart/form-data" in same modal

### ISSUE THREAD

**Issue by choonoi** [nyroDev/nyroModal#16]
when I try to upload file in modal or just submit form with enctype="multipart/form-data" 
it will get error.

example . i create link "view profile" and open the modal window then in "view profile" page it have form field include file upload enctype="multipart/form-data".
and submit in that form i will show error. how should i fix it?

**Comment by nyroDev** [comment]
I can't reproduce this bug.
Could you provide a page where we can see it please?
Please also indicate in which browser it's occuring.

**Comment by choonoi** [comment]
sorry for late answer.
i just tested on my computer.
u can try by using upload and submit in same modal.

Follow the step .
1.pop up modal and in that modal have upload field and.
2.upload file in that modal and in the form use class=nyroModal enctype="multipart/form-data" with to working in same modal then u will see the error

problem is.
upload from Normal page to Modal : OK
upload from Modal to Modal : got error

**Comment by choonoi** [comment]
OPS! sorry , missing closed :( how do i open again?

**Comment by stfr** [comment]
This bug appears again in the new version.

**Comment by stfr** [comment]
My mistake, it does not appear in the new version, but take care to your button name attribute.

When using the nyroModalFormFile mode( upload form for example) , "An error occured" appears if your button name is "submit". It doesn't with classic forms or another button name ...

Yay.
