### ISSUE TITLE
Switching the focus to the lightbox

### ISSUE THREAD

**Issue by lawyip** [nyroDev/nyroModal#160]
Hi, 

I'm trying to create a page, abc.html, whenever this page is loaded, a popup will appear on load, and switch the focus to the popup page.

Here's my setup:
in abc.html's <body> tag:

<script type="text/javascript">
$(function() {
  $('.nyroModal').nyroModal();
  $.nmManual('prompt.html');
});
</script>

I've tried to use the callbacks to switch the focus, such as:

<script type="text/javascript">
$(function() {
  $('.nyroModal').nyroModal();
  $.nmManual('prompt.html', {callbacks: {afterShowCont: function(){$('iframe[name="nyroModalIframeForm"]').focus();}}});
});
</script>

I've tried to replace $('iframe[name="nyroModalIframeForm"]') with other scripts but still can't get it to work.
Can anyone please help? Thanks.

**Comment by nyroDev** [comment]
The problem is that jQuery will works only when the page is loaded...
To do what you want, my recommandation will be:
1. Add HTML element to show your loading modal by yourself
2. Once the page is loaded, hide your loading stuff and open your nyroModal
