### ISSUE TITLE
Parameter "title" is ignored by nmData and nmObj

### ISSUE THREAD

**Issue by biasot** [nyroDev/nyroModal#162]
I using latest nyroModal with jQuery 1.7.1
            $.nmObj({ title: "Attention!" });
            $.nmData("Hello!", { title: "Attention!" });
 produce no errors, but specified title isn't displayed.

**Comment by nyroDev** [comment]
The title filter is not intended to work this way.
The only way it works for now is a title attribute on the opener element.
