### ISSUE TITLE
simple hidden div showing next/previous buttons?

### ISSUE THREAD

**Issue by MACscr** [nyroDev/nyroModal#163]
I have a simple div with a form in in it and when it appears, i cant use the top part of the form because the next/previous buttons appear when i go to those fields. Why are they even appearing? How can i disable them? This is a single div and there is no gallery or multiple elements for it to flip through. Thoughts?

**Comment by nyroDev** [comment]
You may have a rel attribute on your form, and some other element on the page that have the same rel attribute.
Simply remove or change this rel attribute and you might be good.

**Comment by MACscr** [comment]
I dont have any rel attributes on the form, but the anchor linking to the form has rel="tooltip" and so do a few others. Which i need to keep. Is there a way to just disable grouping that way?

**Comment by MACscr** [comment]
I have a tabular data with links on the last column for each like so:

`<li><a href="#edit_user" class="edit open-modal get_user" user-id="2" title="Edit Item" rel="tooltip">edit</a></li>
<li><a href="#" class="delete" title="Delete Item" rel="tooltip">delete</a></li>`

The user-id changes obviously, but thats about it.

**Comment by nyroDev** [comment]
If you don't need the gallery feature, simply don't include it.
If you need it, use a init function with the callbacks settings to : 
1. check if the gallery filter is activated (nm._hasFilter('gallery')
2. check if you are in the case you don't want the gallery (nm.opener.is('[rel="tooltip"]') ?)
3. remove the gallery filter (nm._delFilter('gallery'))

**Comment by maxbato** [comment]
Hi,
I see you have mentioned "f you don't need the gallery feature, simply don't include it." Can you explain how this is done? I have the same issue here and need a way to disable the gallery feature but keep my rel attributes. My current call to nyroModal is as follows:
$(function () {
    $('.nyroModal').nyroModal();

```
$('.nyro_custom').each(function () {
                            var a = $(this);
    var sp = a.attr('rel').split(/[,x]/);

    var wid = sp[0];
    var hei = sp[1];

    a.nyroModal({
sizes: {
            minW: wid,
            minH: hei,
            w: wid,
            h: hei
        }
    });
});
});
```
