### ISSUE TITLE
No repositioning when 2nd modal dialog called from 1st modal dialog

### ISSUE THREAD

**Issue by synio-wesley** [nyroDev/nyroModal#168]
Triggering the bug:
- http://nyromodal.nyrodev.com/
- Open first demo: Ajax
- Try to resize the window - seems to reposition/resize the modal dialog as well
- Click on "new modal" inside the modal dialog
- Try to resize the window again - modal dialog does not reposition/resize anymore!
- Close the modal dialog
- Open first demo: Ajax again
- Try to resize the window - modal dialog still does not reposition/resize

Expected behaviour:

Window repositions/resizes after window resize
for modal dialogs which have been opened from within another modal dialog.

Not sure if I am missing something?
Thanks in advance for your time :)

**Comment by nyroDev** [comment]
Thanks for your report, the fix will be available soon online
