### ISSUE TITLE
resize and close subsequently goes blank content

### ISSUE THREAD

**Issue by terasaka2k** [nyroDev/nyroModal#169]
If I call .resize() and .close() subsequently, modal doesn't close and content goes blank.

A example code which cause the issue :
 $.nmTop().resize(); $.nmTop().close()

Is there any way to interrupt resizing and then close correctly?

Thank you.

**Comment by tommykamkcm** [comment]
Hi, I have the same problem as well. I tried to call resize() after doing some HTML update (display a loading bar) inside the nyroModal, then called close() once the data processing completed.

There was no javascript error reported by Firebug and the nyroModal won't close.

Hope this information will be useful for the team to fix this bug.

Thank you very much
