### ISSUE TITLE
padding/size settings in nyroModal v2

### ISSUE THREAD

**Issue by clarkin** [nyroDev/nyroModal#17]
I've recently updated from nyroModal 1.6.2 to v2 and I'm having trouble getting my modal windows to look how they used to. 

I can't seem to get a window with 0 padding within it, or the specific size I want. My old code was:
    $.nyroModalSettings({
        padding: 0,
        height: 600,
        width: 600
    });
I'm trying to do the same with the sizes property but it doesn't seem to work:
    $('.nyroModal').nyroModal({ 
        sizes: { 
            initW: 600, 
            initH: 600, 
            w: 600, 
            h: 600, 
            minW: 600, 
            minH: 600, 
            wMargin: 0, 
            hMargin: 0
        } 
    });

**Comment by nyroDev** [comment]
The padding is now set by CSS, in the margin value of .nyroModalCont.

In the sizes object, only the minW and minH properties can be used to parameter the minumum sizes of the element. The othere values are overwritten by the code.

**Comment by clarkin** [comment]
Cheers, was able to get it working by tinkering with the nyroModal.css.

**Comment by nyroDev** [comment]
Great, thanks for letting us know.

**Comment by impaler** [comment]
Thankyou, can please remove the sizes options from the official webpage http://nyromodal.nyrodev.com/, this was driving me crazy.
