### ISSUE TITLE
Hidden <div> and swfobject with OnEvent in IE8

### ISSUE THREAD

**Issue by ActiveNation** [nyroDev/nyroModal#170]
This is a very convoluted problem that occurs in only a specific set of circumstances, but has been affecting me greatly.  Let me start off by telling what I am attempting to achieve.  I have a video that is being played on a client's website, specifically the homepage.  The video was uploaded to YouTube, and now I am embedding it on the website, via a nyroModal window.  The window should open when someone visits the page, begin playing automatically, and when the video ends, the window should close.

I have already achieved most of this, including embedding the video, using the swfobject method, into a nyroModal window, using the hidden <div> method, with the correct parameters in place to make it open when someone visits the page and play automatically.  The problem comes at the end of the video.  In Chrome, Firefox, and IE9, it seems to work fine, but in IE8, the onevent trigger for closing the window (using OnStateChange -> If newstate ===0 parent.$.nmTop().Close();) does not fire.  Having tested it, in the right circumstances, when I use another page being embedded, instead of a hidden div, the event will fire, and can do a number of things, including resetting the video, but it cannot close the window.

Something in the combination between IE8, the hidden <div> method, and the swfObject OnStateChange will not work.  If it wasn't for the fact that according to the most recent statistics I have found, approximately 10% of the world is still using IE8, I wouldn't even bother with this, but until that number goes down a lot more, I have to be sure that the video will close in all browsers.  Do you have any idea why this problem might be occurhttp://github.github.com/github-flavored-markdown/ing?

For a live demo, you can see the video at http://www.wrosslocklearlaw.com/videotest.shtml.  The important code is pasted below:

```
<link type="text/javascript" href="js/jquery.nyroModal.custom.js" />
<script type="text/javascript" src="jquery.min.js"></script>
<link rel="stylesheet" href="css/nyroModal.css" type="text/css" media="screen" />
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<script type="text/javascript" src="js/jquery.nyroModal.custom.js"></script>
<!--[if IE 6]>
    <script type="text/javascript" src="js/jquery.nyroModal-ie6.min.js"></script>
<![endif]-->
<script type="text/javascript">
$(function() {
  $('.nyroModal').nyroModal();
});
</script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/swfobject/2.2/swfobject.js"></script>    
  <script type="text/javascript">
    function onYouTubePlayerReady(playerId) {
      ytplayer = document.getElementById("myytplayer");
      ytplayer.addEventListener("onStateChange", "onytplayerStateChange");
    }

    function onytplayerStateChange(newState) {
       if (newState == 0) {
       // Code to reset the video
       parent.$.nmTop().Close();   }
    }</script>
    <script type="text/javascript">

    var params = { allowScriptAccess: "always" };
    var atts = { id: "myytplayer" };
    swfobject.embedSWF("http://www.youtube.com/v/mJG8P13muHA?enablejsapi=1&playerapiid=ytplayer&version=3&autoplay=1&controls=0&showinfo=0&rel=0",
                   "YouTube", "560", "315", "8", null, null, params, atts);

  </script>
<script type="text/javascript">
$(function() {
$.nmManual('#hidden');
});
</script>
</head>

<body>
<div id="hidden"><div id="YouTube" style="display: none; width: 560px;">
                You need Flash player 8+ and JavaScript enabled to view this video.

            </div>
</div>
```

Any help would be appreciated.

**Comment by nyroDev** [comment]
it could be better if you execute the execute the code to create the youtube player after the modal is already shown.
That might fix a lot of problem.
Basically, you'll use the afterShowCont callback to do your stuff.
