### ISSUE TITLE
Speed up after trigger

### ISSUE THREAD

**Issue by llahnoraa** [nyroDev/nyroModal#171]
When you click any link to trigger nyromodal, it have "normal" speed. What it would be nice if it can be set to "fast" or "slow". Unless if you have that already, can you please update the doc so I can update it? Thanks!

**Comment by nyroDev** [comment]
You can do that by overwriting all animation that are set in the fade anim filter.
Check out the file https://github.com/nyroDev/nyroModal/blob/master/js/jquery.nyroModal.anims.fade.js to find out how is is set up.
