### ISSUE TITLE
nyroModal prev/next problem with ie7&ie8 only

### ISSUE THREAD

**Issue by Ben4fi** [nyroDev/nyroModal#173]
Hi All,
I installed a nyroModal that work perfectly with all browsers, except ie7 and ie8 (work with ie9, fox, chrome, safari, etc...)
When I click the "Prev" or "Next", I get a javascript error "Line 5, car 23853, invalid argument" and the modal stay on the loading gif...

Any idea to fix this?

Thank you

**Comment by Ben4fi** [comment]
I forget to add some details :
nyroModal v2.0.0
jquery 1.7.1

**Comment by nyroDev** [comment]
Is the problem still ocurring?
Any place where I can see it?
In the meantime, i'm closing the issue.
