### ISSUE TITLE
cursor jumps to top of page (firefox)

### ISSUE THREAD

**Issue by Schampanja** [nyroDev/nyroModal#175]
Hi there!!!
When I use NyroModal in a link to a pic or an Iframe everything wors normal and fine, except the Website jumps to the top.
This happens only in Firefox. In IE and Chrome everything works fine...

Example:
<a class="nyroModal" title="foobar" href="./title_8e3e799d4fe0e9d.jpg">Foo Bar</a>

Is there anyone with an idea.

Thanks a lot!

Dave

**Comment by acrolyt** [comment]
Did you find a solution for this?

Thanks
Marco

**Comment by nyroDev** [comment]
This issues seems to have disappear.

**Comment by acrolyt** [comment]
In my case it was just my bad code : ) It did jump to the top because of a href="#"
