### ISSUE TITLE
Submit form with the target to a iframe and close window

### ISSUE THREAD

**Issue by lfsantle** [nyroDev/nyroModal#18]
Hello, I need to submit a form with the target to a iframe and after he sued to close the window.

have:

the index that calls nyroModal
index2 with the form and the iframe
and the prc_teste.html which has the function

$(function() {
    $.nmTop().close();
    alert("Área alterada com sucesso!");
});

but when he talks about ending nmTop is not a function.

**Comment by nyroDev** [comment]
try to use parent.$.nmTop().close();

NB : both pages have to be in the same domain name.
