### ISSUE TITLE
Verify Closing of Modal

### ISSUE THREAD

**Issue by sgsweb** [nyroDev/nyroModal#180]
When the user closes the modal using escape key, clicking outside the modal, or clicking the X, I like to popup another modal to ask them if they are sure.  Similar to a confirm javascript api.  The problem is that there is no way to prevent a closing using the beforeClose callback.  That is, I cannot send back a false from the beforeClose callback to prevent the closing of the modal.  What is the best method for doing this?

sgs.

**Comment by nyroDev** [comment]
See commits d42cd1f307e6fadab776a1ba319343baad845b7c and 6fc323277c3199e4d8099ca1565919096794fc34

You'll be able to do something like:

```
$.nmFilters({
    custom: {
        close: function(nm) {
            if (!nm._confirmClosed) {
                if (confirm('Are you sure you want to close it?')) {
                    nm._confirmClosed = true;
                    nm.close();
                }
                return false;
            }
        }
    }
});
```
