### ISSUE TITLE
Resize when content change

### ISSUE THREAD

**Issue by manuh73** [nyroDev/nyroModal#181]
How to have nyroModal dialog resize properly when content changed?
Already try $.nmTop().resize(true); does nothing
Content of the hidden div is an image and a tools div
Size of the image is not known when the content is shown the first time.

**Comment by nyroDev** [comment]
$.nmTop().resize(true); should work properly.
If you use image,it could be a good idea to set width and height on them.
If you cannot do that, you'll have to add callback on the afterShowCont function to find out when your images are loaded.
Then, you'll trigger $.nmTop().resize(true); (or simply nm.resize(true) as you'll get the nm object in the afterShowCont function.)
