### ISSUE TITLE
Replace Modal with NyroModal

### ISSUE THREAD

**Issue by yorismith** [nyroDev/nyroModal#182]
I am completely new to jquery and ajax thing, I found this plugin from friend's site, and it seems perfect fit for my existing project which I am trying to make my own personal website, I have ajax code to query data from xml and php using jquery modal windows to display the content, unfortunately modal windows can't handle content that contain javascript inside, so I need to replace the popup windows with this NyroModal, however, newbie like me have no idea where to start to replace that popup windows

This is my ajax/jquery code...

http://codepaste.net/hdc9dj

Is there anyway to replace modal dialog  windows with this plugin?

Thank you very much for great plugin...I use it for my photo gallery, so smooth and beautiful transition...

Respectfully,
Yori

**Comment by nyroDev** [comment]
Unforunately, the codepaste has expired.
If you still need help, please reopen an issue.
