### ISSUE TITLE
TypeError: Object #<Object> has no method 'nyroModal'  on Magento

### ISSUE THREAD

**Issue by serotonine** [nyroDev/nyroModal#185]
Hello,

My nyroModal.js is charged before my script and my JQuery noConflict works (tested with the script commented)

I working on Magento ver. 1.11.2.0 . I put a jQuery.noConflict(); alos on the bottom of  nyroModal.js (is it useful ?)

a href="women/size-guide" target="_blank" class="size-guide">Size guide</a

script type="text/javascript"
            jQuery.noConflict();
            jQuery(function() { 
            //jQuery('.size-guide').click(function(e){  e.preventDefault(); alert('click'); });
            jQuery('.size-guide').nyroModal(); 
            });
/script

Any help ?

**Comment by serotonine** [comment]
Ok I found the solution. I share it in case of ....

Place your script in an external file.js and add it after the nyroModal.js one (and of course after the jQuery.js  add)

<code>&lsaquo;action method="addJs">&lsaquo;script>nyroModal/js/ file.js&lsaquo;/script>&lsaquo;/action>
&lsaquo;action method="addJs">&lsaquo;script>nyroModal/js/nyroModal.js&lsaquo;/script>&lsaquo;/action></code>

in file.js write : 
<code> jQuery.noConflict();</code>
<code>jQuery(function($) {  $('.myClass').nyroModal(); });</code>

Oh ! and  look about the version of your jQuery.js. NyroModal uses the jQuery 1.7 method on()

**Comment by nyroDev** [comment]
Didn't got everything as I don't anything about Magento,n but you find out how to solve your problem.
