### ISSUE TITLE
nyromodal not working in FF

### ISSUE THREAD

**Issue by girishsokate** [nyroDev/nyroModal#187]
i m using a anchor tag for calling the nyromodal html page, but unable to view it. only loading image is displayed

**Comment by jyeager11** [comment]
Similar problem here, but on both IE9 and FF15 (latest version of each) : Screen goes dark, but nothing appears. Triple-checked the code.

The same code was working a few months ago.

**Comment by nyroDev** [comment]
Is it still occuring? If so, please reopen an issue with code sample, or better, link to see the problem.
