### ISSUE TITLE
this.on is not a function

### ISSUE THREAD

**Issue by jrsmith17** [nyroDev/nyroModal#188]
I was trying to find an alternative to jquery tools overlay since it doesn't work with drupal 7 due to a jquery version conflict. On the smart resize function its throwing an "Unhandled Error: 'this.on' is not a function". Is this also because a jquery version conflict? I think I read that nyro needs jquery 1.7 or higher but drupal 7 supports only up to 1.5.2

**Comment by n40i** [comment]
Have you tried using the jQuery update plugin? http://drupal.org/project/jquery_update

**Comment by nyroDev** [comment]
Yes, this is mainly a jQuery versionb problem. I guess this have been solved since.
