### ISSUE TITLE
Modal z-index missing?

### ISSUE THREAD

**Issue by bung** [nyroDev/nyroModal#19]
Hello,

On my site, certain things are showing up above the modal and certain arent, however _none_ of them have any absolute positioning / z-indexing. It appears the modal you're using doesn't use any z-indexing either, this didn't happen with the last version, any tips?

Thanks.

**Comment by bung** [comment]
you also have an error on line 101 of your css, background-position: right: 20%;

**Comment by megatom** [comment]
i added some css to nyroModal.css
.nyroModalBg z-index:997
.nyroModalCloseButton z-index:999
.nyroModalTitle z-index:999
.nyroModalCont z-index:998

**Comment by nyroDev** [comment]
As said megatom, if you need to z-index nyromodal, you can set your own in your CSS file.

Thanks for the error reporting, I'll commit a fix for that.

**Comment by nyroDev** [comment]
Add imageRegex parameter in nmObject and use it in image filter. #Closed by 8f2a6a44afda25bf8f98d6d577b293f4ea0e02f2
Fix CSS error. Closed by 8f2a6a44afda25bf8f98d6d577b293f4ea0e02f2
Add header and footer parameter in nmObject. Closed by 8f2a6a44afda25bf8f98d6d577b293f4ea0e02f2
