### ISSUE TITLE
has no method 'nmCall'

### ISSUE THREAD

**Issue by barryross** [nyroDev/nyroModal#190]
Hi, I am trying to open my nyroModal window on a page load.  I have it working properly when a user clicks on a link, but the following produces "#hiddenContent" has no method 'nmCall' in the javascript developer console  - any ideas?

jQuery(document).ready(function(){
 jQuery('#hiddenContent').nmCall();

};

**Comment by nyroDev** [comment]
What you need to call is:

```
$.nmManual('#hiddenContent');
```
