### ISSUE TITLE
nyroModal + Ckeditor submit and reload problem

### ISSUE THREAD

**Issue by TOTOleHero** [nyroDev/nyroModal#191]
Hello,

When we use nyroModal and Ckeditor as embedded form in popup, there is a problem at reloading form. Ckeditor refuse to display it.

in Firebug the error message is : NS_NOINTERFACE: Component returned failure code: 0x80004002 (NS_NOINTERFACE) [nsIWebProgress.DOMWindow]

I think it's problem with ckeditor instance and DOM when Ajax is use.

To explain my problem, i have join attachment with PHP sources of my problem.

http://depositfiles.com/files/l0vxx0rzu

Same question to ckeditor community : http://cksource.com/forums/viewtopic.php?f=6&t=27048

Thank

**Comment by nyroDev** [comment]
As you said, it's more related to ckeditor than nyroModal.
Maybe you should do some clean up in the beforeHideCont, but I can't help you more as I don't know ckeditor.
