### ISSUE TITLE
Reset Form's .submit() handler after modal is opened

### ISSUE THREAD

**Issue by mgasparel** [nyroDev/nyroModal#193]
I have a large form (5k+ rows), and each row contains a checkbox (and other form elements)

I am using the nyroModal to submit the form to a confirmation page, displayed via a modal window, which will display all the selected records and their respective values. I have 2 buttons at the bottom of the confirmation modal: "Cancel" and "Process"

What I want to do is rig the "Process" button to submit the form to a new page, but the handler has been replaced with the call to my modal window. (when I try and submit the form via the "Process" button, the modal simply reloads itself)

When I'm setting up the modal, I'm rigging my "Cancel" and "Proceed" buttons via the callbacks:
afterShowCont: function(nm) {
    $('.close-modal').click(function(){
        nm.close();
    });
    $('#process-actions').click(function(){
        $('#benefits_form').attr('action', 'processBenefitsEnrollment.asp');
        $('#benefits_form').submit();
    });
}

Is there any way to reset the form's submit handler, or any other way to achieve my desired result?

**Comment by nyroDev** [comment]
I'm guessing that your form also have a nyroModal class or something like that.
Thus, you're from is binded to be loaded in a modal when it's shown inside the modal.
What you should do to make it work (if I well understood your problem) is : 

``` javascript
afterShowCont: function(nm) {
    $('.close-modal').click(function(){
        nm.close();
    });
    $('#process-actions').click(function(){
        $('#benefits_form')
            .attr('action', 'processBenefitsEnrollment.asp')
            .off('submit.nyroModal')
            .submit();
    });
}
```
