### ISSUE TITLE
passing data for ajax via javascript 

### ISSUE THREAD

**Issue by ben-hultin** [nyroDev/nyroModal#200]
I know you can submit data via form submit, but I have one input field that I need to use for three different modal buttons. Is there a way to pass the data from that input field via a jquery selector and val() to a url like so:

var input = $('#input_field').attr('id').val();
$('#response_iframe').attr('src', 'ajax-page.php?input='+input);

I have tried this but that value does not get passed unless I place it in .click() function. When I do that though, the modal box does not work. What can I do about this?

Thanks a lot

**Comment by nyroDev** [comment]
Did you try by updating the href of your anchor when the field is updated.
That should work correclty.
