### ISSUE TITLE
Resize, again

### ISSUE THREAD

**Issue by tlhackque** [nyroDev/nyroModal#202]
This ought to be simple...

I have a div that is activated by a modal link.  This works. when the link is opened (with $(...).click()),
the div opens as a modal.  The setup is very simple: $('.modalLinks").nyroModal().  No options, no other calls.

While the modal is open, some events (clicks that cause ajax transactions/responses, if it matters) occur.

I use jQuery to add or replace content to this div.  $(...).html("new content"), or append().  The content of this div is simple html: h1, text, sometimes a small form.

Scroll bars appear on the div - the modal does not expand, despite the fact that there is plenty of screen space for it.  

I have tried several approaches to calling resize(true), which ought to fix this.  None have worked.

How, _exactly_, do I tell nyroModal that content has changed?  Please, a concrete example.  $.nmTop().resize(true) does not work.  Although I've seen several errors, the
current one has the content disappearing and a blank box shown.

Specifically, If I set a breakpoint on the $.nmTop().resize(true) line, I can see my content in the nyroModal div.  If I step over that call, the content disappears.  (Firebug shows it as really disappeared, not just hidden.)

If I don't call resize, the div works as expected - except that it is necessary to manually scroll.

This is nyroModal.latest (as of a day or two ago):
     \* nyroModal v2.0.0
     \* Core
     *
     \* Commit \1ff104065fb155520ad2c6e52ec1753473ae7bf0 (10/21/2012) *

Firefox 16.0.2, windows 7, 64-bit OS.

Many thanks in advance.

**Comment by tlhackque** [comment]
A little more data that may be a clue.  In stepping through the code, I saw the content being deleted, but didn't understand exactly why.  resize seems to copy the dom's 'hidden child elements", do some math, then delete them.  Unfortunately, that's the data I just loaded.

However, as an experiment, I set a 2000 msec (2 sec) timeout function after updating the div:
window.setTimeout(function () { .nmTop().resize(true);}, 2000);

With this, the div shows the content as before, then when the timer goes of, the div resizes!

So it seems to me that there is a window between when the div is updated / the modal clicked, and when it is safe to call resize.    Obviously, this is not a satisfactory solution, but it does seem to shed some light on what is going on.

Perhaps with this additional information you can provide some advice - or if this is a bug, a fix.

Many thanks.

**Comment by tlhackque** [comment]
Some of the intermittent failures are explained because $.nmTop() returns undef when a modal isn't (yet) active.

This is not like the rest of jQuery, which is happy to work on an empty set.  I think $.nmTop().resize(true) should work even if no modal is active.

at a minimum, it should do nothing.  It would be reasonable for it to mark the next modal to open to be resized.

The current behavior requires code like   $.nmTop()  && $.nmTop().resize(true) ...

This still doesn't explain content disappearing.

**Comment by tlhackque** [comment]
I guess I'm learning slowly.

The copies that nm makes are very confusing when one tries to update html content in an open modal because the copy and the original have the same id attributes.   It's not legal to have 2 elements with the same id. 

So $('#something').html("new content") doesn't always work - it selects one and stops. Sometimes that's the dom of the modal div, and sometimes its the original data.

Why are these copies necessary?  I thought with domCopy false (the default), nm would move the dom as required.

Can I prevent the copies?  Or can nm make the copies have unique IDs - and arrange that the ID originally coded is the one that is available for dynamic updates (open or closed)?  

It seems as though to provide real-time updates to an open modal, I will have to close, update and re-open.  This doesn't make sense - it will not be a good user experience.

**Comment by tlhackque** [comment]
This seems to be resolved, after a lot of digging.  Here are the key points that belong in the documentation:

Triggering a modal - e.g. by clicking on an "opener" link, creates a new instance, every time.  This is why I was seeing nested copies and blank screens.  To prevent this, use code like this:

```
function loadModalDiv (newContent) {
   var modalObject = $('#modalOpener').data('nmObj'),
      mIsOpen = modalObject._open;

      $('#modalDataContainer').html(newContent);

      if( mIsOpen ) {
        modalObject.resize(true);
      } else {
        $('#modalOpener').click();
      }
}
```

This will ensure that you only create one modal, and that updates resize.

$.nmTop() currently will return undefined if no modal is open.  Thus unconditional $.nmTop().resize(true) will crash
if no modal is open.

I still believe that $.nmTop() should return something that allows unconditional $.nmTop().resize(true), without code like:

```
var topModal = $.nmTop();
    if( defined topModal && topModal._open ) {
         topModal.resize(true);
}
```

With this understanding, things appear to be working.  I hope this note helps someone else avoid the traps that I fell into.  Explaining this in the documentation would be a good thing.

**Comment by Blackskyliner** [comment]
Also a possibility if you have more than one modal w/o using given hack of yours:

```
$(window).smartresize(function(){
                        $.nmTop().getInternal()._resize();
                        $.nmTop().resize(true);
                    });
```

thogh it will sneak peak a bit of CPU as it will use both different methods of resizal... The first one for initial dialogs and the second one for follow-ups. Don't know why they are even different... I think its because the normal $w.smartresize uses the _internal of the first initialized dialog. funny though that the _resize() it calls won't work on follow-up modals (like through links/forms or calling nyromodal twice) but then only resize(true/false) works directly.

Even though its dirty - it solves the whole problem on my whole site setup.

**Comment by nyroDev** [comment]
@tlhackque I'm sorry, I didn't follow you all the way. What was your problem simply? Did you manage to fix it? Please reopen an issue with details and link to show the error.
