### ISSUE TITLE
Can't use enctype with nyroModalManual

### ISSUE THREAD

**Issue by carloand** [nyroDev/nyroModal#204]
I use jquery.validate to validate a form inside a nyromodal. In the validate options I have submitHandler: function(form) { $(form).nyroModalManual();}
In the form tag, I have ENCTYPE="multipart/form-data". 
When I submit I get an error "The requested content cannot be loaded. Please try again later."
Is there any way I can solve the problem?
Thank you for your help

**Comment by nyroDev** [comment]
Do you still have the problem? Please provide a link or something in order to debug it.
be free to reopen the issue if needed.
