### ISSUE TITLE
resize height includes hidden elements

### ISSUE THREAD

**Issue by croghan** [nyroDev/nyroModal#207]
There are 3 sections that can be shown on this modal (attached image).  Nyromodal calculates the height of everything hidden or visible for class nyroModalCont.  Unless I'm missing a parameter (which I really hope I am), the only way to fix this is to set the height after resize.  If it's not an issue and you have suggestions how best to handle this, I'd appreciate it.

![modal](https://f.cloud.github.com/assets/3117298/29977/963db3e4-4df8-11e2-8208-9cdfbf3df920.png)

**Comment by nyroDev** [comment]
The question here is: How is hidden the element, and most of all, when?
If the element are hidden before the show and before the modal calculation, it should works correctly.
Please reopen the issue if you still need help by providing a link or some code.
