### ISSUE TITLE
form array not sent 

### ISSUE THREAD

**Issue by choonoi** [nyroDev/nyroModal#208]
my from in modal
- nyroModal v2.0.0
- Commit 1ff104065fb155520ad2c6e52ec1753473ae7bf0 (10/21/2012) \* 

``` html
<form class='nyroModal' method='post'>
<input type='checkbox' name='lang[]' value='en' checked>EN
<input type='checkbox' name='lang[]' value='jp' checked>JP
<input type='checkbox' name='lang[]' value='cn' checked>CN
<input type='submit'>
</form>
```

when i submit form it should be
lang[0]=>en
lang[1]=>jp
lang[2]=>cn

BUT it's not

it got only

land[0]=>cn

I used to use nyroModal previous version and it's work fine.
- nyroModal v2.0.0
  - Core
    *
  - Commit 9c52b4050b940e9ef26c (09/17/2011) \* 

Please help

**Comment by pjam** [comment]
Hi.

I noticed this too a couple of weeks ago.
I had a form with a multiple select in it that worked fine, but after a nyromodal update, only one value passed through, even if more than one option was selected. I developed a crude but effective fix that I can share with you, to use if you're in a hurry and can't wait for a proper fix.

Just change the load function of the form filter to look like this:

``` javascript
load: function(nm) {
                var data = {};
                $.map(nm.opener.serializeArray(), function(d) {
                if( d.name.substring(d.name.length-2) == '[]' )
                {
                    var fieldName = d.name.substring(0, d.name.length-2);
                    if( !(fieldName in data) )
                    data[fieldName] = [];
                    data[fieldName].push(d.value);
                }
                else
                      data[d.name] = d.value;
                });
                if (nm.store.form.sel)
                    data[nm.selIndicator] = nm.store.form.sel.substring(1);
                $.ajax($.extend(true, { type : 'get', dataType : 'text' }, nm.ajax || {}, {
                    url: nm.store.form.url,
                    data: data,
                    type: nm.opener.attr('method') ? nm.opener.attr('method') : undefined,
                    success: function(data) {
                        nm._setCont(data, nm.store.form.sel);
                    },
                    error: function(jqXHR) {
                        nm._error(jqXHR);
                    }
                }));
            }
```

**Comment by choonoi** [comment]
I did update my code without passing that kind of value.

But,Thank you so much pjam
It's work perfectly.

**Comment by jckhunt4** [comment]
i update the js file and it's works fine.
thanks pjam.
