### ISSUE TITLE
html5 input validation

### ISSUE THREAD

**Issue by acrolyt** [nyroDev/nyroModal#211]
When you open this page in Chrome

http://upload.gestalten.com/modalwindow.html

and click on the link on top to open a modal window and click on "submit" inside of it
the Chrome tooltips for input-validation aren't showing?

Any ideas if this is a chrome-, nyroModal-, or my-code issue?

Thanks in advance!

**Comment by nyroDev** [comment]
Seem to be fixed now by chrome.
