### ISSUE TITLE
YouTube Video Gallery

### ISSUE THREAD

**Issue by jQueried** [nyroDev/nyroModal#212]
I'm not really sure how or why this is happening, but the YouTube gallery example (the hockey game) on the nyromodal site works fine and then when I cut and paste it onto a page of my own I get an error that states that the publisher of the content does not allow it to be displayed in a frame.  A few days ago it was working fine.

I just switched from using the sample version to this one and it works:
http://www.youtube.com/embed/

Not really sure why it would make a difference unless YouTube is changing it's coding policies.

**Comment by nyroDev** [comment]
seems like a youtube error at the time, and not directly related to nyormodal.
Thanks anyway for the feedback.
