### ISSUE TITLE
Problem with image filter regex

### ISSUE THREAD

**Issue by jhollingerAndCulture** [nyroDev/nyroModal#216]
Because you have defined the regex as a string, you need to use double backslashes to escape the characters.  You have to escape the backslashes in the JS string in order for a single backslash to carry through for the regex.  Your expression currently is matching for 0 or more of the letter 's' instead of matching whitespace like you intended.

[^\.]\.(jpg|jpeg|png|tiff|gif|bmp)\s*$

**Comment by nyroDev** [comment]
Thanks for the feedback!
