### ISSUE TITLE
Modal pops at bottom of page?

### ISSUE THREAD

**Issue by coz3r** [nyroDev/nyroModal#217]
I have a link to a nyroModal and when I click the Modal pops at bottum of the page.
The Link is a in a jquery custom scroll div - could this be whats causing the postioning?

http://www.verticalvisionartstudios.com/fabrication.php

picture/link is at the bottom of the custom scroll div

**Comment by nyroDev** [comment]
It might be related to the custom scroll as you mentionned it.
The link doesn't wrk anymore.
Please reopen the issue if you still need help.
