### ISSUE TITLE
Modal Not Opening at Proper Height - Firefox

### ISSUE THREAD

**Issue by markrichter** [nyroDev/nyroModal#218]
In newer versions of Firefox (specifically I was able to re-create this on 19.0.2 and 20.0 on the Mac and 20.0 on the PC), when I click the video thumbnail in the right column of this site, the modal window does not open at the proper height. Works fine in all other browsers.

http://www.travelhq.com/cp/ctsDemo/index.html

**Comment by nyroDev** [comment]
Fix your iframe HTML element first.
<iframeframeborder="0" allowfullscreen style="overflow:hidden; height:480px; width:640px;">
