### ISSUE TITLE
using jquery validation with nyromodal v2

### ISSUE THREAD

**Issue by kaederukawa7** [nyroDev/nyroModal#22]
how to validation with nyromodal v2. On v1.6.x i use this code :

<script language="javascript">
    $("#updateform").validate({
        submitHandler: function(form) {
            $(form).nyroModalManual();
        }   
    });
</script>

and it's working, but not on this version.
anyone could help me ???

Tq

**Comment by nyroDev** [comment]
Did you read the new documentation?

The nyroModalManual function doesn't exist anymore.
To replace it, you can use:
$(form).nyroModal().nmCall();

**Comment by joshcutler** [comment]
There seems to be an infinite loop issue if you have a form that has multipart (for file input).  

Any idea how to work around this?

**Comment by amnesia7** [comment]
I have a button that launches a hidden modal that contains a file upload form. 

The form has `validForm` validation on it as per the nyromodal homepage demo.

I'm then using `$(form).nyroModal().nmCall();` for the ajax form submission of the file upload form when it passes validation as per the example and I get an infinite loop as well.

Did either of you (@joshcutler , @nyroDev) manage to find a way around this. I'm using an up-to-date version (only downloaded today).
