### ISSUE TITLE
How to implement _delFilter() ? and the nyroModal in general

### ISSUE THREAD

**Issue by ghost** [nyroDev/nyroModal#220]
Hello ,

Is someone could give me an example of how to use the nyroModal functions please ? It's not evident at all.
in my nyroModalConfig.js : 
$('#myDiv').nyroModal(
{

}
)

Thank you !!

**Comment by nyroDev** [comment]
The _delFilter is used in filter when a filter has to be removed in order to work correctly.
That the case for the formFile filter which remove the form filter.
The form with data isn't loaded in the same way than normal form, and normal form loading should be completly skipped out.
