### ISSUE TITLE
How to use the plugin without href?

### ISSUE THREAD

**Issue by samuelrs** [nyroDev/nyroModal#221]
Hello, I am trying to use this great plugin modal, but I want the modal open according click of a button, so do not have a url to pass to the plugin.
  Really do not know how to do without it. any suggestions?

  I tried using the "$. NmData", but the resize this way does not work. And honestly the resize is the major attraction of this plugin.
  Could someone help me?

**Comment by nyroDev** [comment]
You may use the $.nmManual('url'); function instead.
