### ISSUE TITLE
nyroModal not working when click on image

### ISSUE THREAD

**Issue by ghost** [nyroDev/nyroModal#224]
//Working
a href="blabla" class="nyroModal">Ajax</>
//Not working
img title="test" src="include/images/add.png" alt="test" class="nyroModal"

$(function nyroModal() {
        $('.nyroModal').nyroModal();
    });

working as planned or not?

**Comment by nyroDev** [comment]
it won't work, because there is no href attribute on the image.
We don't know what to load and what to show on the image.
Add a surring anchor with the class nyromodal to make it works.
