### ISSUE TITLE
I don't want to have the loader

### ISSUE THREAD

**Issue by serotonine** [nyroDev/nyroModal#225]
Hello,

I have an iframe nyroModal opening in a nyromodal popup on a jquery ajax event.

I don't want to have the nyroModal loader but How to do ? I tried all sort of settings but no way. May I use nmObj({elts: {load: false}}) ? it doesn't work

//my implementation
complete : function(d){  jQuery("#add-basket-btn").nyroModal( ).nmCall();   }

Could someone help me please ?

**Comment by nyroDev** [comment]
Firstly, you can remove the loading gif from the CSS.
Then, you can edit the fade anim filters to make the showLoad anim immediat (using show intsead of fadeIne)
