### ISSUE TITLE
Positioning issue.

### ISSUE THREAD

**Issue by pratham2003** [nyroDev/nyroModal#226]
Why does this not set the appropriate margins?
I'm assuming it auto centers. I tried to override the size and resize call back.. But no luck.. Also not much documentation provided about it..

```
$.nmData('Box 1', { sizes : { 
    wMargin: -500,  // Horizontal margin
    hMargin: -500   // Vertical margin);
    }
});
```

**Comment by nyroDev** [comment]
There is also a check to not make a popin going outside the viewport.
That's why your code is not working.
What is the purpose of doing that?

Please reopen the issue if you think I can still help.
