### ISSUE TITLE
afterShowCont callback does seem to pass the textarea.val() correctly

### ISSUE THREAD

**Issue by dathelen** [nyroDev/nyroModal#229]
Trying to accomplish something like this:

```
$('.nyroModal').nyroModal({
    callbacks: {
             afterShowCont: function(nm) {
                          $('#comment').jqEasyCounter(); 

              }
                 }

    });   
```

comment is a text area.  Inside the jqEasyCounter there is a call to $this.val() and that always has a value of 0 even when there is text in the field.  If i move the  $('#comment').jqEasyCounter();  outside of nyromodal it seems to work fine.   As anyone seen this before?  I am using the latest stable version

**Comment by nyroDev** [comment]
Did you check if there's another #comment element on the page?
Do you still need help with that?
Please reopen the issue if so.
