### ISSUE TITLE
how to use custom "CLOSE" to close iFrame page?

### ISSUE THREAD

**Issue by choonoi** [nyroDev/nyroModal#23]
i would like to use custom close from iframe how can i do?
because when i click close modal i want it to return some script to main page.

example in A tag 

onclick="add_picture('my_photo.png');  class="nyroModalClose"

it's working with aJax but not working with iFrame

**Comment by nyroDev** [comment]
To do something like that, you'll have to call a script on the parent frame.

The code you need to call is:
parent.$.nmTop().close();

**Comment by cancunjc** [comment]
this is not working in the iFrame samples... It took me many hours to find this solution.

**Comment by batonmedia** [comment]
I have the same problem (
