### ISSUE TITLE
with a xhtml page the dialog is empty

### ISSUE THREAD

**Issue by Perlette** [nyroDev/nyroModal#231]
I added the link to my page (xhtml):

```
<a href="#" onclick="muestraVentanaModal('pages/rank/newjsp.jsp');">
                                Agregar nuevo premio (1)
                            </a>
```

When i click on this link the modal dialog appeared with the content of newjsp.jsp

But when i replaced the jsp by a xhtml, with the same link, the modal dialog is empty. Do you know why?

**Comment by nyroDev** [comment]
Is there a place where I can see it live please?
Reopen the issue if you still need help.
