### ISSUE TITLE
Better _debug() function.

### ISSUE THREAD

**Issue by Blackskyliner** [nyroDev/nyroModal#234]
Just a proposal:

``` javascript
            _debug: function() {
                if (this.debug && window.console && window.console.log)
                    window.console.log.apply(window.console, arguments);
            }
```

This way you can also debug more than one value with one call. As console.log does support '{...*}' or better: it prints all 'arguments' it gets.

**Comment by nyroDev** [comment]
Thanks for your great feeback!
