### ISSUE TITLE
Modal window is not working on page 2 of infinite scroll

### ISSUE THREAD

**Issue by dann2013** [nyroDev/nyroModal#236]
Hi,
I try to use nyromodal on a page which have infinite scroll implemented, but modal windows don't work on second page. 
Is there a known conflict between these two plugins ? 
Could you tell me how can I fix this problem ?
Thank you

**Comment by Blackskyliner** [comment]
how do you bind nyromodal to the elements?
You need bind it to $(document).on('click', function(){ /_do nyromodal on this element_/ }) so it will also work on dynamically loaded elements.

Else you may need to bind the onclick on newly loaded elements to call nyromodal.

**Comment by nyroDev** [comment]
Thanks @Blackskyliner, you said everything.
