### ISSUE TITLE
  This content cannot be displayed in a frame 

### ISSUE THREAD

**Issue by sugappriyaodessa** [nyroDev/nyroModal#237]
Hi 

I used nyromodel v2 with jQuery 1.9.0 . I was trying to diplay the youtube video. But its showing following error "This content cannot be displayed in a frame"

Code:
$(document).ready(function() {
            $('.nyroModal').nyroModal();
});
"html a href="http://www.youtube.com/watch?v=lddUnv1R5y0" class="nyroModal">Youtube (Via Embedly filter"
any solutions plz.

**Comment by Blackskyliner** [comment]
You may use the embedd link... else you would include the whole youtube site.

like this: https://www.youtube.com/embed/lddUnv1R5y0
alternative, old way: http://www.youtube.com/v/lddUnv1R5y0?version=3

**Comment by nyroDev** [comment]
I added a new youtube filter that you can use in replacement of embedly.
