### ISSUE TITLE
Close $.nmData()

### ISSUE THREAD

**Issue by DiV666** [nyroDev/nyroModal#238]
Hi, great job with nyroModal

I'm trying to close a window but do not know how to do this, I explain

```
    // Loading window
    $.nmData('<img src="loading.gif" alt="Loading..." />', {'stack' : true, 'modal' : true});

    // Ajax call
    $.ajax({
        cache: false,
        type: $(form).attr('method'),
        url: $(form).attr('action'),
        data: $(form).serialize(),
        success: function(data) {
            // I try close loading window with
            $.nmTop().close();
            // but not work...
        }
    });
```

Thank you.

**Comment by Blackskyliner** [comment]
"but not work..." - specify the error you get.
Try enabling the debug in _internal and watch at which callback it stucks.
console.log() the $.nmTop() and see if there is any modal, if not try to find out why. 

Note: the modal must be opened! So call open() before even trying to call close() else there may be no modal on top of the stack. (only displayed/opened modals will be on the stack as they are only pushed in the modal stack if open() was called, as this function actually pushes it onto the stack)

**Comment by nyroDev** [comment]
Thanks @Blackskyliner for you answer.
@DiV666 Please let us know if you still need help.
