### ISSUE TITLE
Disabling the gallery feature

### ISSUE THREAD

**Issue by maxbato** [nyroDev/nyroModal#239]
Hi,
I see you have mentioned "If you don't need the gallery feature, simply don't include it." Can you explain how this is done? I need a way to disable the gallery feature but keep my rel attributes. 
My current call to nyroModal is as follows:

```
$(function () {
$('.nyroModal').nyroModal();

$('.nyro_custom').each(function () {
                            var a = $(this);
    var sp = a.attr('rel').split(/[,x]/);

    var wid = sp[0];
    var hei = sp[1];

    a.nyroModal({
sizes: {
            minW: wid,
            minH: hei,
            w: wid,
            h: hei
        }
    });
});
});
```

**Comment by Blackskyliner** [comment]
He meant that you simply don't include it at all.
So just delete the code from the nyromodal.custom.js file which regards to the gallery.

There may also be a way to just delete it through unsetting the gallery filter, or at least null/undefine it

```
$.nmFilters({
        gallery: undefined // or null or [] you need to test a bit here...
});
```

Beware! As this will disable it globally!

**Comment by nyroDev** [comment]
Thanks @Blackskyliner for your great answer.
