### ISSUE TITLE
Simple modal doesn't work

### ISSUE THREAD

**Issue by megatom** [nyroDev/nyroModal#24]
See here my example:
http://www.deine-berge.de/test/nyro.html
Whats wrong with this?

**Comment by nyroDev** [comment]
You need to include filters. For instance, you'll need the iframe filter.

**Comment by megatom** [comment]
Hmm sorry I tried it before with the complete custom .js an it didnt work too, but that must be a different failure by me.
Now it works fine.
THX.

**Comment by megatom** [comment]
Unfortunately I cant simply replace my old 1.6.2.js with this new custom.js :(
What else I have to do to "upgrade" to v2 ?

**Comment by nyroDev** [comment]
the version was rewrite from scratch.
You have to include the JS file, as well as the JS file with conditionnal comment for IE6.
You also need to update the CSS and to bind by yourself your .nyroModal stuff (it's not done anymore automatically by the script)

**Comment by megatom** [comment]
Phew seems not so easy to port my complete site from 1.6.2 to 2.0.
There are various functions that seems not to work:
If i send a form, the submit button is not in my POST data,
If i send a form with enctype:multipart/form-data in opera: an error accured,
And how can i switch off the log function? Firebug fires all the changes, but i dont want to see them...
