### ISSUE TITLE
Project dead and needs new Maintainer?

### ISSUE THREAD

**Issue by Blackskyliner** [nyroDev/nyroModal#240]
@nyroDev are you even reading the issues here and try fixing at least some of them or is this whole project/library abondend?

**Comment by nyroDev** [comment]
I didn't do anything for a whole time.
But I'm trying to getting back.
I saw a lot of answer in the issue, and you seem pretty good.

I'll be glad to get some pull request and things like that if you're willing to ;)

**Comment by Blackskyliner** [comment]
I am sparse at time by myselft atm, I just use it in a productive environment so I digged nearly 10 times through all the code to get it doing what I want it to do. I will open some issues with some requests which make the whole lib more productive. But I don't know if I get the time to create some PR's... time will tell. But good to see that you are back at maintaining.

**Comment by nyroDev** [comment]
Great, thanks for your time anyway;)
