### ISSUE TITLE
Lightbox don't display properly 

### ISSUE THREAD

**Issue by laughtman** [nyroDev/nyroModal#241]
I didn't code this site but i discovered the issue and checked for the plugin and it brings me here.
I'm not sure if this is a known issue or it's a matter of customization, i'd like to see if this can be solved by maybe update nyroModal or changing to another plugin.
![captura de pantalla 2014-06-06 a la s 14 39 24](https://cloud.githubusercontent.com/assets/7818835/3205171/9b703d2c-edb2-11e3-9490-b534cbbe0e3c.png)
Thanks.

Here's a link: http://landrover-mexico.com/mx/discovery/photos-and-videos/

**Comment by nyroDev** [comment]
You had changed to another lightbox plugin, so we can't see what was going on.
Sorry for the long delay...
