### ISSUE TITLE
Iframe redirect to page and have modal close and page load in full browser

### ISSUE THREAD

**Issue by WebPhenom** [nyroDev/nyroModal#243]
Is there a way to have the Iframe redirect to page and when that page loads, have the modal close and force the page load in full browser?  On the redirect html page is there some code that would make the page load outside of the modal, closing the modal ?

**Comment by nyroDev** [comment]
You could do that only if the iframe loaded is in the same domain than the opener.
You'll do that with the code : 
parent.document.location.href = 'yournewpage';

If you need to close the modal from an iframe:
parent.$.nmTop().close();
