### ISSUE TITLE
Using the form submission feature

### ISSUE THREAD

**Issue by russellrobinson** [nyroDev/nyroModal#244]
Just a note for others...

Don't include the `name` attribute in your submit button.

This breaks nyroModal for some reason:
`<input type="submit" name="submit" value="Pay now">`

but this works fine:
`<input type="submit" value="Pay now">`

**Comment by nyroDev** [comment]
I just tested, and it seems to work correclty.
The only thing is that the value of the submitted button is not send.

Are you still seeing this issue?
If so, could you provide some URL or code to experience it?
