### ISSUE TITLE
Fix the background scrolling

### ISSUE THREAD

**Issue by Blackskyliner** [nyroDev/nyroModal#245]
Its just a -more or less- simple fix.

After opening the Modal add "overflow: hidden" to the body Element of the DOM, thus not scrolling the background if you scroll more than there is inside the modal.

I do this currently this way:

``` javascript
$(this).nyroModal({
            callbacks: {
                beforeShowBg: function(){
                    $('body').css('overflow', 'hidden');
                },
                afterHideBg: function(){
                    $('body').css('overflow', '');
                }
           }
})
```

A more generic solution would save the previous overflow state though ;)

**Comment by nyroDev** [comment]
Some devs like to keep the page scrolling at the bottom of the page.
So I guess this fix has to be implemented by dev, when they need it.
I created a new label in order to find this kind of issue quickly

**Comment by Blackskyliner** [comment]
Well, maybe document on how to fix this in the docs then. As it is kind of hard to realize how to do if you just getting started with HTML/CSS/JS. Because who will search the issues fur such label?

Maybe creating some tipps.md in some doc folder or a Wiki entry on GH?
