### ISSUE TITLE
Modal content appears behind table

### ISSUE THREAD

**Issue by exwyezed** [nyroDev/nyroModal#247]
The content is appearing behind a table: http://screencast.com/t/0mlXGOoyw

**Comment by nyroDev** [comment]
It seems you have a z-index problem.
By default, nyroModal doesn't set z-index as it's not mandatory if you're not using them on your website.

In order to fix it, you can update the CSS as follow:

```
.nyroModalBg {z-index: 1000;}
.nyroModalCont {z-index: 1001;}
.nmReposition {z-index: 1002;}
```

(change the z-index to be greater than your uppest z-index)

**Comment by exwyezed** [comment]
Just added a new issue check it out please.

I'm not sure if you can help me with it, if you can help me I'll appreciate it.

Thanks,
Alfonso.

2014-10-23 9:49 GMT+02:00 Nyro notifications@github.com:
