### ISSUE TITLE
Modal stop working (table navigation)

### ISSUE THREAD

**Issue by exwyezed** [nyroDev/nyroModal#248]
Video: http://screencast.com/t/33JZbDi2l
I can't figure out how I could make it works.

I tried different ways to fire it:

$( '#test' ).on('click', function(){

```
  $.nmManual(this.href);

  })
```

 $(function(){
        $('.nyroModal').nyroModal();
      });

**Comment by exwyezed** [comment]
It's working with this:

 time=setInterval(function(){
          $('.nyroModal').nyroModal();
},1000);

Seems it needs to be re-executed it everytime I click next page..etc

**Comment by nyroDev** [comment]
nyroModal has to be called everytime the DOM is changed in order to bind the click events.
So when you change page, just call $('.nyroModal').nyroModal(); once the content is fully added in the page.
