### ISSUE TITLE
Photo Gallery Question

### ISSUE THREAD

**Issue by jblack1992** [nyroDev/nyroModal#249]
Hey guys not sure if this just a lack of knowledge on HTML or what. But when I use the photo gallery code you guys offer on the main page of http://nyromodal.nyrodev.com/ on multiple galleries in an unordered list it joins them into 1 gallery instead of having them separate. Could I possibly get some input on how to make them show up separately without having to take them out of the unordered list? This is the page i'm using it on: http://www.txdot.gov/inside-txdot/district/san-antonio/san-antonio-traffic-jam.html in the "Photo Library" area. The first text link is supposed to house the first 4 images and the second is supposed to house the last 5. 
Thanks for any input!
Josh

**Comment by nyroDev** [comment]
The rel gallery is used to create multiple gallery.
You can for instance use rel="gal1" for the links in the first gallery and rel="gal2" for the second list.

**Comment by jblack1992** [comment]
Awesome! Thank you for the prompt response! Ill try that out.

**Comment by jblack1992** [comment]
That worked! Thanks a ton!
