### ISSUE TITLE
No easy way to change image matching regexp

### ISSUE THREAD

**Issue by marek-saji** [nyroDev/nyroModal#25]
In nyroModal 1.x `regexImage` setting allowed to easily manipulate which links were treated as images.

**Comment by nyroDev** [comment]
Add imageRegex parameter in nmObject and use it in image filter. #Closed by 8f2a6a44afda25bf8f98d6d577b293f4ea0e02f2
Fix CSS error. Closed by 8f2a6a44afda25bf8f98d6d577b293f4ea0e02f2
Add header and footer parameter in nmObject. Closed by 8f2a6a44afda25bf8f98d6d577b293f4ea0e02f2
