### ISSUE TITLE
Close button cannot reposition when the modal execute resize

### ISSUE THREAD

**Issue by PaulCong** [nyroDev/nyroModal#252]
I have an issue is when i call the resize function, the popup size is changed, but the close button cannot be repositioned. below is my code:
 $.nmManual(url
        , {
            callbacks: {
                afterShowCont: function (nm) {
                    nm.sizes.w = width;
                    nm.sizes.h = height;
                    nm.resize();
                }
            }
        }
    );
the close button just stay the original place that the modal not call the resize function.

**Comment by nyroDev** [comment]
You should use nm.resize(true); in order to indicates that the size of your content has changed.
NB : you shouldn't set the width and height manually, this ahs to be calcultaed regarding the DOM element sizes.
If you need minimum size, use min-heigth and min-width in your CSS.

**Comment by ghost** [comment]
Hum actually I'm struggling with the same issue.
When loading html that contains images using nmManual or nmData, nm.resize doesn't seem to update the close button position...

For example :

```
$.nmData('<div class="my_class"><div><img src="http://lorempixel.com/1600/800/transport/6/"></div><div class="text"><h1>Transport</h1><p class="description">I like trains</p></div></div>', {
    "callbacks":{
        "afterShowCont": function(nm){
            nm.resize(true);
        }
    }
}
);
```

I get this output on FF39 and chrome:
![capture](https://cloud.githubusercontent.com/assets/3534129/8694732/3b31399e-2ae1-11e5-9508-f32db8c07efb.JPG)
