### ISSUE TITLE
Call nyromodal from AJAX 

### ISSUE THREAD

**Issue by jQueried** [nyroDev/nyroModal#253]
I'm trying to get nyroModal to display an element in a lightbox, in this case an image, after an AJAX form submission has taken place.  However, I've tried several variations and nothing seems to work so my last attempt was with nmCall, but tried nm as well.  Can't seem to get it to load from the showRequest or showResponse functions.  Wasn't sure if it was a conflict between jquery and nyroModal, but I've seen other samples where nm was called from jquery.  I must be missing something.

``` javascript
$(document).ready(function() { 
    var options = { 
        target:        '##output1',  
        beforeSubmit:  showRequest,   
        success:       showResponse   
    }; 

    $('##theform').ajaxForm(options); 
}); 

function showRequest(formData, jqForm, options) { 
    var queryString = $.param(formData); 
    return true; 
} 

function showResponse(responseText, statusText, xhr, $form)  { 
    $('##aDivElement').nyroModalManual(); // THIS SEEMS TO WORK BUT BEHAVES STRANGELY
} 
```

**Comment by nyroDev** [comment]
If you want to open a nyroModal, you should use the nmManual call.
The first argument is the url (##aDivElement in your example I guess) and the second are nyroModal options (not required).
So, the call in showResponse should looks like:

``` javascript
$.nmManual('##aDivElement');
```
