### ISSUE TITLE
Multiple popups

### ISSUE THREAD

**Issue by KMantas** [nyroDev/nyroModal#255]
Does multiple popups work? For me it doesnt seem to. 

here is an example:
http://jsfiddle.net/Rep9P/8/
after closing 2nd popup 1st is not shown and also content of 1st popup is not going back to original place

**Comment by nyroDev** [comment]
Fixes jsFiddle:
http://jsfiddle.net/Rep9P/9/

**Comment by KMantas** [comment]
oh, thats great. thanks!
