### ISSUE TITLE
$.nyroModalSettings is not a function

### ISSUE THREAD

**Issue by PandaWood** [nyroDev/nyroModal#259]
I wonder if someone would document what should be used instead of $.nyroModalSettings - which has disappeared upgrading from 1.6 to 2.0 - there is no mention of it in the changes and I see no obvious replacement.

**Comment by Ryan-Haines** [comment]
Anyone have an answer to this?

**Comment by PandaWood** [comment]
Hey @Ryan-Haines - I didn't figure it out and moved on to use another library

**Comment by PandaWood** [comment]
I have a more specific question about this issue - with code - but it was never answered - https://github.com/nyroDev/nyroModal/issues/261
