### ISSUE TITLE
YouTube (youtube video) issue with nyroModal

### ISSUE THREAD

**Issue by atifgulzar** [nyroDev/nyroModal#26]
Hi, I have a page with a object of YouTube (youtube video), and when I
click on some nyroModal link, in Firefox, IE7, IE8, the video overlay the frame of the
nyroModal.
I tried to use z-index in a div with the youtube video inside, but the
problem could not be resolved.

Solution required. Any Help?

Thanks.

**Comment by nyroDev** [comment]
On the demo page, it seems to work for me.
Could you post a page where we can watch the bug?
