### ISSUE TITLE
how it works?

### ISSUE THREAD

**Issue by captnx** [nyroDev/nyroModal#3]
Sorry to trouble you again.

I used the "create.php" to create my own "nyroModal.js". I chose all the items.
This is my first try on using it, but it doesn't work, is there any mistakes?

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<head>
  <script src="jquery-1.4.4.min.js" type="text/javascript"></script>
  <script src="js/jquery.nyroModal.custom.js" type="text/javascript"></script>
  <link rel="stylesheet" href="styles/nyroModal.css" type="text/css" media="screen" />
</head>

<body>
  <a href="http://www.baidu.com" class="nyroModal">test</a>
</body>

**Comment by nyroDev** [comment]
I can't see anything. Please provide a link where we can see the page or somethign else to watch the code.
Or maybe you figured out how to fix your problem. If so, please cose this issue.
