### ISSUE TITLE
Height Width params

### ISSUE THREAD

**Issue by jQueried** [nyroDev/nyroModal#30]
I just started using nyroModal and passing width and height doesn't appear to be working so I'm trying to find more examples of the syntax used.  I set the minWidth and minHeight to a value as a default and tried to alter another layer using it, but it's not responding in any browser I've tried (e.g. IE8, FF3+, Chrome).  Do you have more samples of the options usage as well?

$(function() {
    $('.class1.nyroModal a').nyroModal();
    $('#anotherLayer a').nyroModal({
    width: 700,
    height: 400
    });
});

**Comment by batonmedia** [comment]
Which version of nyroModal do you use?

**Comment by wietsewarendorff** [comment]
This works for me:
    <script type="text/javascript">
    $(function() {
        $('.nyroModal').nyroModal({
            sizes: {
                minH: 550,
                minW: 750
            }
        });
    });
</script>
<a href="modal.php" class="nyroModal">open up!</a>

**Comment by nyroDev** [comment]
What's the status of this Issue please?
