### ISSUE TITLE
How to install it ?

### ISSUE THREAD

**Issue by rzepa** [nyroDev/nyroModal#32]
Hi,

I want install it but I can't ;/
I add to head 
- jquery.nyroModal.js and nyroModal.css and jquery-1.4.4.min.js
- <script type="text/javascript"> $(function() { $('#nyroModal').nyroModal(); }); </script>

I add this button in body 
<a href="advert_details.php?id=1" id="nyroModal" class="nyroModal">Ajax Filtering Content #blabla</a>

I want open in popup my url but it is open new tabs ;/

**Comment by nyroDev** [comment]
Did you add jQuery library before nyroModal?
Please provide a test page.

**Comment by rzepa** [comment]
Yes I add jQuery before nyroModal.
I did test. I save this page as html http://nyromodal.nyrodev.com/embedly.php and source is the same but the link doesn't work ;/ It is the most simple test but I don't know why it is work ;/

**Comment by nyroDev** [comment]
Did you include filters on nyroModal?
Because jquery.nyroModal.js alon will not work, that's just the core. It NEEDS at least the link filter to work in your case.
Link me your page on your server.

**Comment by rzepa** [comment]
Filters what that means ?
I checked now test.html and is work! test.html but link on the page it is not work. The link is on left top corner here # and I trie open php file in popup.

**Comment by nyroDev** [comment]
Plese don't hot link the files on my server.
Filters as it's defined in the nyroModal doc...

Use the regular download on nyroModal and it'll works.

**Comment by rzepa** [comment]
I download all package from this site nad in js folder are jquery.nyroModal.filters.*

**Comment by rzepa** [comment]
It's work thx !
