### ISSUE TITLE
IE8 style problem and YouTube layer problem

### ISSUE THREAD

**Issue by jQueried** [nyroDev/nyroModal#36]
Have noticed that when nyromodal is viewed in IE8 after scrolling a portion of the way down, the nyromodal window opens out of the viewable area as if it is fixed at the top of page.  In other words, upon scrolling down the page and clicking a link that activates nyromodal, the nyromodal lightbox appears out of site and can only be seen by scrolling up again.  The black opacity area also doesn't fill the screen.  This only happens with IE.  In Firefox it does not happen.  I suspect there is a style issue that requires a fix.

Also, even with YouTube set to transparent and given an appropriate z-index, as well as nyromodal's z-index, YouTube is still showing on top of nyromodal.

Love nyro, just can't figure out what's happening at the moment.

**Comment by nyroDev** [comment]
Did you set a doctype at the very top line of your HTML code source?

**Comment by jQueried** [comment]
You can close this out, that did the trick.  Didn't realize the site was missing that.  Thanks.

**Comment by jQueried** [comment]
This apparently is still an issue.  What doctype does it have to have at this point?  If I use anything prior to 

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd">

the same behavior occurs.  

It will not work with the following either I'm afraid.

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">

Thanks.

**Comment by jQueried** [comment]
Also noticed that even when a current doctype is used YouTube still appears on top of the lightbox when it opens.

**Comment by jQueried** [comment]
Just wanted to set this straight.  WMODE was needed and was thought to already be in place.  Once that was corrected the problem was solved as far as the YouTube layer exceeding the nyro layer's z-index.  Only remaining problem is the background with the 50% opacity doesn't reach the full height of the screen in IE8 for some reason. Tried updating the style sheet, but so far nothing changed.  Perhaps something is cached.  Will try again tomorrow.  Sorry for any confusion.

**Comment by nyroDev** [comment]
Please post a page where we can see the problem.
