### ISSUE TITLE
Always load iframe without using target='_blank'

### ISSUE THREAD

**Issue by jicho** [nyroDev/nyroModal#37]
How do I always open a followed link in a iframe without using "target='_blank'"?

I'm trying to figure out how it should work... But nothing working :( This is wat I have:

<script type="text/javascript">
$(function () {
    $("a.overlay").nyroModal({
        filter: ['iframeForm'],
        loadFilter: 'iframeForm'
    });
});
</script>

But that does not work... And I can't find any other config options... Using the Manual option gives the same results :(

Thanks for your help!

**Comment by nyroDev** [comment]
In order to force the iframe filter, you should do something like:
$.nmManual('url', { callbacks: { initFilters: function(nm) { nm.filters.push('link'); nm.filters.push('iframe'); } } });

And it might work.
I didn't test it, so please let me know.

**Comment by jicho** [comment]
Hi,

It took a lot of time to test is, but great news! It works :)

Tnx!
