### ISSUE TITLE
Filter: how to implement?

### ISSUE THREAD

**Issue by wietsewarendorff** [nyroDev/nyroModal#38]
Hi,

I want to redirect the page as soon as the nyroModal window closes. I understand I need a filter (?), but how do I do this? My current script is:

```
<script type="text/javascript">
$(function() {
    $('.nyroModal').nyroModal({
        sizes: {
            minH: 550,
            minW: 750
        }
    });
});
```

</script>

Thanks in advance!
- Wietse

**Comment by nyroDev** [comment]
You'll have to use something like:
    $('.nyroModal').nyroModal({
      sizes: {
        minH: 550,
        minW: 750
      },
      callbacks: {
        afterClose: function(nm) {
          // Do whatever you want
        }
      }
    });

This is the easiest way.
You don't need to use filter in your case, as it's easy and the callbacsk settings is here for the rescue.

**Comment by wietsewarendorff** [comment]
Perfect! Thanks!
