### ISSUE TITLE
image links opens as raw data

### ISSUE THREAD

**Issue by latompa** [nyroDev/nyroModal#4]
I have
    <a href="view_large.jpg?1234" class="large_image">click me</a>

when I add nyroModal to it, the image opens up in a modal with raw data like this
https://skitch.com/thomasolausson/rgf7s/image-raw-data

any ideas why? (chrome and safari)

**Comment by latompa** [comment]
If i remove the ?1234 part, nyroModal works.
My local rails server adds timestamps to assets.

It seems that regular expression in jquery.nyroModal.filters.image.js might need to be modified. 

Image links can have query parameters as well, so URLs might not end with just .jpg/.gif

**Comment by nyroDev** [comment]
If you replace

return (new RegExp('[^.].(jpg|jpeg|png|tiff|gif|bmp)\s*$', 'i')).test(nm.opener.attr('href'));

with 

return (new RegExp('[^.].(jpg|jpeg|png|tiff|gif|bmp)', 'i')).test(nm.opener.attr('href'));

Does it work well?

**Comment by latompa** [comment]
Yea, the regexp fixes it. Thank you.
