### ISSUE TITLE
iframe target blank size

### ISSUE THREAD

**Issue by cleibesouza** [nyroDev/nyroModal#41]
I'm trying to open an nyromodal window with an iframe using target blank. 
I need the iframe to be a specific size. I can't make the iframe look bigger. It's always the same size regardless what I do. Here's how I'm doing it:
$(function() {
    $('.nyroModal').nyroModal({
            sizes:{
                minH:800, 
                 minW:800
             }
        });
    });

My link looks like this:
&lt;a class="nyroModal"  href="anyPage.php" " target="_blank"&gt;Open&lt;/a&gt;

Right now it opens a modal with 800X800 as specified, but the contents of the iframe load in a different size (600 X 400) and I don't know where these dimensions come from or how to overwrite this.

Thanks for any help. 

Than

**Comment by nyroDev** [comment]
In the default CSS, you'll find:
.nyroModalCont iframe {
  width: 600px;
  height: 400px;
}

update these rules and you'll be able to set the iframe size as you wish.
