### ISSUE TITLE
Setting up height/width and then gracefully closing the box

### ISSUE THREAD

**Issue by krishnakummar** [nyroDev/nyroModal#45]
I just started using nyroModal. I tried my best to understand and get my code working but in vain. This is what I am trying to accomplish. I am showing a form, having "Save" link, on the modalbox and on clicking th Save button an ajax request is sent to update the DB (works fine till this point) and on ajax success I want to show "Update Success!" on the modal box(it should resize to fit this content) and after a sec the modal box should fadeout. I am just looking for a basic syntax to do this. Any help is appreciated. This is my current code.

```
$("#createtaskslink").live("click",function(){
    $.ajax({url:"ajax/tasksajax.php"
        ,async: false
        ,data: { action: 1
        ,taskdesc:'hello' }
        ,success:function(data){
```

// i want to resize now to show just Update Success
                $.nmData("Update Success!",{
                    callbacks: {  
                    afterShowCont: function(nm){
                        nm.close();
                    }
                }
                }); 
            }
        });
    });
1. How can I resize the modalbox automatically to fit to the content ?
2. How can I close the modalbox after a second ?

Thanks,
Krishna.

**Comment by nyroDev** [comment]
1. The modal should resize regarding the content. If not, please check your CSS if you have something setting minimum sizes on it.
2. Simply use a timeout to call what's inside the doc:
   $.nmTop().close();
