### ISSUE TITLE
First image clicked does not close

### ISSUE THREAD

**Issue by rorylysaght** [nyroDev/nyroModal#48]
(apologies if I'm re-posting - somehow my first issue went straight to 'closed')

Whatever image is first clicked in a session does not close - so if I start on image 5, then go to 6, 7, 8 etc. Then if I open 5 again and click next, #5 stays in the background.  Next image and background overlay #5, but it never goes away.  Only way is to click X to close both.
Then issue remains until page refresh.  

Consistent between FF and IE.

I can show this happening on a live page if anyone has any clues.

**Comment by nyroDev** [comment]
Sorry for the long delay.
Could you provide a live page to see the bug please?
