### ISSUE TITLE
missing : after property id

### ISSUE THREAD

**Issue by zafsta** [nyroDev/nyroModal#5]
There is a syntax error on line 1113:

1112:   url: nm.store.link.url,
1113:   data: nm.store.link.sel ? {nm.selIndicator: nm.store.link.sel} : undefined,
1114:   success: function(data) {

This is from version 2.0.0.

**Comment by nyroDev** [comment]
In which browser do you see this error?

**Comment by jethroma** [comment]
I am seeing this too in firefox (Linux firefox 3.6.13). I guess something to do with the order that things are evaluated. Maybe put parenthesis around it?

**Comment by nyroDev** [comment]
Fix selIndicator not correctly send
Fix syntax error. Closed by 3af6de1a599d518fce43681a11fe47a57c4b3b50. Closed by 3af6de1a599d518fce43681a11fe47a57c4b3b50
