### ISSUE TITLE
Trouble With the 2.0 Basic Install

### ISSUE THREAD

**Issue by cdcbrian** [nyroDev/nyroModal#50]
I recently upgraded a site I was working on to the 2.0 version of the plug-in, but can't get the basic set-up to work properly. I've posted two test pages to demonstrate the issue:

http://www.crystdesign.com/github/basic.html (the basic install—view the source for details)
http://www.crystdesign.com/github/custom.html (using the custom version of the .js file—view the source for details)

The Basic set-up won't open in a nyroModal window but the custom version will. I'm at a loss—I've poured over the code repeatedly and haven't been able figure out what to do.

I can't use the custom version of the .js file on the actual site because the Links, Gallery and related filters/add-ons interfere with the functionality of the pages being shown within the modal window.

Any help would be appreciated!

**Comment by nyroDev** [comment]
you HAVE to use a custom build.
jquery.nyroModal.js is only providing basic feature and need at least obne filter to work..

**Comment by cdcbrian** [comment]
Thanks for the quick reply! I really appreciate it.

So I've updated a custom .js file to include the Links filter (but no other filters)—since it appears as though none of the other filters work without it and I need only the basics. Here's the link:

http://www.crystdesign.com/github/custom.html

But when the nyroModal opens the new page (1.html), when you click through the previous and next links, some of the links stop working. And if you close the modal window, the link on that page no longer works.

So why is the Links filter interfering with standard links and how do I prevent that from happening? I don't have a firm grasp on what the Links filter is doing.

Thanks again for your help, I really appreciate it!
