### ISSUE TITLE
Links Filter Turning Off Links

### ISSUE THREAD

**Issue by cdcbrian** [nyroDev/nyroModal#52]
So I've updated a custom .js file to include the Links filter (but no other filters)—since it appears as though none of the other filters work without it and I need only the basics. Here's the link:

http://www.crystdesign.com/github/custom.html

But when the nyroModal opens the new page (1.html), when you click through the previous and next links, some of the links stop working. And if you close the modal window, the link on that page no longer works.

So why is the Links filter interfering with standard links and how do I prevent that from happening? I don't have a firm grasp on what the Links filter is doing.

Thanks again for your help, I really appreciate it!

**Comment by nyroDev** [comment]
Sorry for the long delay.
Please try to redownload the last version and test again.
Let me know if it's working.

**Comment by cdcbrian** [comment]
Whatever you did seems to have solved the problem! Updated code here, for those of you who want to see the corrected version:

http://www.crystdesign.com/github2/index.html

Thanks!
