### ISSUE TITLE
Multiple form submit error

### ISSUE THREAD

**Issue by stfr** [nyroDev/nyroModal#56]
Hello, 

If a form is submitted multiple times in the same nyromodal (class nyroModal on <form> element), an error occured  : 

$(_internal.stack[_internal.stack.length - 2]).data("nmObj") is undefined

You can see it  on the nyromodal simple form demo : Open the nyro, submit the form with the button "new modal from a form", and try to resubmit it

Stéphane.

**Comment by nyroDev** [comment]
This bug was already fixed by the last commit.
I just forgot to upload the last version on the project homepage.
Thanks for your report anyway.
