### ISSUE TITLE
multipart/form-data error

### ISSUE THREAD

**Issue by anton000** [nyroDev/nyroModal#57]
also, forms o longer return submit button values
when using multipart/form-data forms, nyromodal return an error.

**Comment by choonoi** [comment]
do u use  enctype="multipart/form-data" or enctype='multipart/form-data'  ?

single quote and double quote  try enctype="multipart/form-data" with double quote. it maybe can.
because in nyroModal filter with "

**Comment by nyroDev** [comment]
any news about this issue?

**Comment by megatom** [comment]
For me it still doesnt't work with single or double quotes.
But i NEVER get the submit button value posted, with or without enctype :(

**Comment by megatom** [comment]
Will this be fixed in an upcoming version?

**Comment by nyroDev** [comment]
Could you post a test page to watch the error in action?

**Comment by megatom** [comment]
Yes of course: http://www.deine-berge.de/test/nyro.html
click on "send form" link will open nyro with submit in it. 
You see the $_POST array do not contain the submit button :(

**Comment by martijnmegens** [comment]
Its an issue with the serializeArray() function:
http://www.google.com/search?q=serializeArray+jquery+submit+value

**Comment by megatom** [comment]
Ok, but it would be very useful if nyroModal would send it anyway on submit, because it is the way the most people check if a form was submitted.

**Comment by nyroDev** [comment]
For now, I don't have any idea how to fix this problem to include the name value of the submit button.
The reason is simple: The bind is done on the submit event of the form, not the click of the submit button.

Adding a bind in the submit button could be your duty for adding an hidden input with the name of your submit button and it's value.
