### ISSUE TITLE
IE8 and Youtube HTML5 embed problem

### ISSUE THREAD

**Issue by ConfusedDave** [nyroDev/nyroModal#58]
I'm trying to use nyroModal in conjunction with YouTube's HTML5 embed code, which uses an iFrame. In IE 8, clicking the close button on the modal window results in a completely black screen. Works fine in all other browsers I've tried (IE 6, IE 7, IE 9 RC, Firefox 3.6.14, Chrome 9, Safari 5.0.3). The player uses Flash on IE 8.

An example page you can look at is http://client.baigent.net/playertest/nyrotube.html - click on the image to trigger the modal window.

**Comment by nyroDev** [comment]
Is this bug still occuring?

**Comment by Patmacessex** [comment]
I have sort of a similair problem... but with chrome.
Video plays fine, tested it in safari, firefox and it works fine.
As soon as I open nyromodal in chrome it works, but when I close the nyromodal box and open another, the controls are partially gone (Fullscreen on the right of the control bar) and it wont play anymore.
Only thing to get it going again "once" is to clear chome's cache files

Any thoughts on this?

You can check it all out at : http://patandjana.co.uk

**Comment by nyroDev** [comment]
I can't see this bug. Is it still occuring?
