### ISSUE TITLE
BUG! Alert in modal , how do i use javascript in nyroModal ?

### ISSUE THREAD

**Issue by choonoi** [nyroDev/nyroModal#59]
i want to use "alert" function when i click open new modal but the alert must in the new modal.

it's working in FF3 but IE7 not work.

```
alert("$message");
```

help me please~

**Comment by nyroDev** [comment]
Please, stop telling there is bug the first you see something not working because of your code...
I can use alert on nyroModal greatly.
So if you want to debug your code, plese Post some sample of your code, or even better, a test page.

**Comment by choonoi** [comment]
sorry to say that , please check here

http://203.151.217.159/test/test_alert.html

when visited that page please click on ALERT link
and use IE 7 it's just simple alert javascript

**Comment by ghost** [comment]
Hi,

how I can user jquery inside nyromodal.
Form example I use nyromodal to open comments of chosen faculty. Now, every comment in table
can be deleted (there is link). I need to use ajax for deleting, so I want to do ajax call with jquery, but it
doesn't work.

I also try alert after click on link, but it also doesn't work.
Here is example image for better understanding:

 http://imageshack.us/photo/my-images/820/exampleh.png/

When I click on blue ico, it should give me alert. It gives me alert when I normally opens this page, but not
when I open this page (list of comments) in nyromodal.

How should I solve this

Thanka,

Amer
