### ISSUE TITLE
modal boxes are always stacked

### ISSUE THREAD

**Issue by jethroma** [nyroDev/nyroModal#6]
I only want 1 modal box to exist... setting stack: false in _nmObj doesn't do it.

**Comment by nyroDev** [comment]
Could you provide more information? maybe a link where we can see the problem?

**Comment by jethroma** [comment]
I am trying to have only 1 modal box to open at a time, and I am creating them by code using nmManual. There doesn't seem to be a way to close the other one before opening a new one, unlike in 1.6.

**Comment by nyroDev** [comment]
Fix stack feature when not enabled. Closed by d6d14e59ffe0320204a03d9c72c563a3bc44959e

**Comment by jethroma** [comment]
Works now. Thanks!
