### ISSUE TITLE
wrong position and size on mobile devices

### ISSUE THREAD

**Issue by FlashJunior** [nyroDev/nyroModal#60]
I tested http://nyromodal.nyrodev.com/#demos on iPad & iPhone.

iPad Screenshot: http://i54.tinypic.com/21mc2u0.png

**Comment by FlashJunior** [comment]
http://code.google.com/p/nyromodal/issues/detail?id=469

**Comment by Filou83** [comment]
Why have you closed the issue? Is there no way to fix the problem?

**Comment by miquelbotanch** [comment]
I solved it with the filter "afterResize"

```
            callbacks: {
                afterResize: function(nm){
                    if( $("div.nyroModalBg").outerHeight() < $(window).outerHeight() ){
                        $("div.nyroModalBg").css("height", $(window).outerHeight());
                    }
                    if ( $("div.nyroModalBg").outerHeight() < $("body").outerHeight() ){
                        $("div.nyroModalBg").css("height", $("body").outerHeight());
                    }
                }
```

probably isn't the cleanest way, but it works.

**Comment by nyroDev** [comment]
This issue semmes to be solved by the update of the iPad.

**Comment by dsldsl** [comment]
Mobile still has lots of UX issues. On the iPhone, when you click into a form field the phone zooms in, and then when you click "done" it zooms a bit out and modal shoots across the screen and you cant see it.  You can see that on the demo site, and it is forcing us to move away from modals in production on our site.  Would love to know if anyone has a fix for this.
