### ISSUE TITLE
loading a javascript with nyroModal

### ISSUE THREAD

**Issue by ghost** [nyroDev/nyroModal#62]
Dear nyroDev,
after looking at nyroModal for a couple of days we wonder how to actually load a simple javascript with nyroModal, i.e. some javascript dealing with .nyroModalCont-wrapped content. Unfortunately http://nyromodal.nyrodev.com/wiki/index.php/Main_Page does not look as if it was maintained any longer. By the way we can't verify a script-tag attribute rel='forceload' to exist. Do you mind us asking for some guidance. 
Thanks a lot

**Comment by nyroDev** [comment]
If you want to load an external script, you have to add the rel="forceLoad" on the script tag.
You could also use the rev="shown" if you need this script to execute once the modal is shown on the screen.
