### ISSUE TITLE
Faded fonts in IE7

### ISSUE THREAD

**Issue by kpatmor** [nyroDev/nyroModal#64]
When you open a dialog in IE7 (at least on my machine), the fonts look washed out or distorted. I am using the modal to open a page in an iframe. When I view the page directly in IE7, the fonts look normal. So it is definitely something to do with the modal.

As well, I tried opening the demos from your nyromodal.nyrodev.com site, and see the same issue there.

Interestingly, in IE6, I do not have the same behavior. Other browsers also do not have the problem.

Any ideas? Is it just my machine?

**Comment by nyroDev** [comment]
I already see this issue.
Unfortunately, I can't do anything about that.
This issue is a jQuery one. It occurs evrytime you're using a fade animation on an element.

**Comment by nyroDev** [comment]
Sorry, I don't have any workarounds for that...

**Comment by kpatmor** [comment]
After some searching/testing, you can fix the problem by putting the following into your endShowContent() function:

```
//fix for IE clear type issues when fading
modal.contentWrapper.each(function() {
    if (typeof this.style.filter && this.style.removeAttribute)
        this.style.removeAttribute("filter");
})
```
