### ISSUE TITLE
Still able to repro the _internal stack issue

### ISSUE THREAD

**Issue by joshcutler** [nyroDev/nyroModal#66]
I am able to get this error to throw consistently with the latest that you have here on github:

$(_internal.stack[_internal.stack.length - 2]).data("nmObj") is undefined
[Break On This Error] this.elts = $(_internal.stack[_in....stack.length-2]).data('nmObj').elts; 

My repro steps are to manually open a modela window:

$(".foo").nm().nmCall();

Then in this window I load another modal, by using .nm() on a link.  This opens correctly.

The 3rd window consistently has problem.  I have a fileform on it and upon submission I get the above error.  I hooked up a debugger and saw that the _internal.stack never moves the nmObj forward as it builds the stack, so if I replace _internal.stack.length - 2 with 0, then it works correctly, however this causes other issues when I try to close the window (since nmTop() references the wrong thing).  Any ideas?

Thanks,
-=Josh

**Comment by joshcutler** [comment]
Btw, I have swapped out a variety of filters and they all fail (not just fileform), on the 3rd modal.  The 2nd happens to work only because length-2 = 0

**Comment by Pasc04** [comment]
Hi, i got the same problem while trying to implement it with MVC 2.

After submitting a form and returning back to the same page, i try to submit the form again but get the same problem as you, with the undefined $(internal.stack[internal.stack.length - 2]).data("nmObj")

however, it worked for me when:
1) i replace internal.stack.length - 2 with 0
2) the stack seems to be populating with other object HTMLFormElement after each submit.
so i used a small function to remove all "unnecessary" object  from the stack

(i'm really not sure if its safe to do it...but it solve my problems without any other issues being cause when i close the window)

Here it is:

   if (this.getInternal().stack.length > 2) 
   {
       for (var i = this.getInternal().stack.length;i!=2;i--) {
            this.getInternal().stack.pop();
       }
   }

i would be happy to have your comment on this.

Thanks
Pasc04

**Comment by joshcutler** [comment]
After looking through the code I realized that nyroModal automatically applies itself to the contents of the modal.  I was hitting this issue because I was manually calling nyroModal() on some elements in my modal.

If you let it automatically do its thing, the state of the stack ends up being correct, just note that you have to use his custom class name "nyroModal" since that is the hardcoded selector.

**Comment by Pasc04** [comment]
thks for the response.

But i'm still getting the same errors after doing as you suggest. 

In my case, i'm submiting a form from my modal and returning on the same page.
i'm using this function to stay on the same page using nyroModal: 

```
 var validForm = $('#myForm').submit(function(e) {
        e.preventDefault();
        validForm.nyroModal().nmCall();
});
```

The problem happens when i'm trying to submit the form again.
It's the only place where i'm calling nyroModal() again. Without it, it just return to a normal page.

Any suggestion?

Thks in advance

**Comment by joshcutler** [comment]
Yeah that is what I was doing and had similar issues.  Try just adding the class "nyroModal" to the form and removing your custom submit handler.  The nyroModal framework should take it from there and maintain the stack correctly.
