### ISSUE TITLE
auto-close after submit

### ISSUE THREAD

**Issue by brincas** [nyroDev/nyroModal#67]
I have a nyromodal working in my site, so far everything is working fine, almost fine,

im using the modal to create a form, my idea is to had a simple form then after submit the data show the modal with a message but i want it to close automatic after all data recorded on the database

on parent window i have

<script type="text/javascript">
$(function() {
     $('.nyroModal').nyroModal({
                closeOnClick: false,
                showCloseButton: true
            });
   });
</script>

on the script opened by the modal
i tried 

$(function() {
       $.nm(close())
});
or 
$(function() {
     $('.nyroModal').nyroModal(close());
});
and all i get is to close the modal but also the parent window :(

any sugestion?

**Comment by nyroDev** [comment]
In the loaded data after the form submission, add something like:
setTimeout(function() {$.nmTop().close();}, 3000);

where 3000 represnts 3 seconds
