### ISSUE TITLE
Please Help - Script Conflict

### ISSUE THREAD

**Issue by Laert** [nyroDev/nyroModal#69]
I'm using the script to display video from vimeo.com on the website. It works on the test page (http://glyfadachurch.com/media-video_test3.htm - click on sermon) where there are no other scripts, but it doesn't work on a test page where there are some other javascripts (http://glyfadachurch.com/media-video_test.htm - click on the movie icon of the first item in the playlist).

Can anyone please tell me where's the conflict and how can the issue be solved?

Thanks a lot!
Laert

**Comment by nyroDev** [comment]
Is it intended to load jQuery 1.1 in your page???

By the way, it's not working because you're using the noConflict mode of jQuery.

Instead of doing:
$(function() {
  $('.nyroModal').nyroModal();
});

Do 
jQuery(function() {
  jQuery('.nyroModal').nyroModal();
});

And it should work.
