### ISSUE TITLE
Size Iframe

### ISSUE THREAD

**Issue by bensg** [nyroDev/nyroModal#70]
I cannot size correctly the Iframe. 
NyroModal v2.0.0

I have the following link:

> <a href="help.html#geo" class="helppage" target="_blank">help</a>

And I defined the following configuration:
<link rel="stylesheet" href="css/nyroModal.css" type="text/css" media="screen" />

<script type="text/javascript" src="js/jquery.nyroModal.custom.js"></script>

<script type="text/javascript">
    $(function() {
        $('.helppage').nyroModal({
            closeOnEscape: false,
            closeOnClick: false,
            minWidth: 950, 
            minHeight: 650

        });
    });
</script>

But my NyroModal popup does not receive the good size, always the default size.

**Comment by bensg** [comment]
I tried with the following configuration but in this case, the internal Iframe keeps the initial size and the NyroModal popup is correct:
$('.helppage').nyroModal({
            closeOnEscape: false,
            closeOnClick: false,
            sizes: {  
                minW: 950,
                minH: 650,  
                initW: 950, 
                initH: 650, 
                w: 950, 
                h: 650, 
                wMargin: 5, 
                hMargin: 5
              }

```
    });
```

I think that the Iframe tag must receive an initial size.

**Comment by nyroDev** [comment]
In the initial CSS, there is a rule to set the default size of an iframe in nyroModal.
.nyroModalCont iframe {
  width: 600px;
  height: 400px;
}

Simply update these rules and it will work.

**Comment by cyberhobo** [comment]
This confused me too - a comment in the documentation for `sizes` would have helped me.

**Comment by vishalmelmatti** [comment]
Hi,

changing the above class in css changes the size of all modals but how can I change the size of nyroModal for a specific modal? 

Thanks

**Comment by vishalmelmatti** [comment]
Hi,

I could manage to achieve the different sizes of nyroModals by following below procedure. This may not be the best way to do it but it worked for me ..

Changing the width of iframe from CSS to 100%

<style>
.nyroModalCont iframe {
    width:100%;
    height: 530px;
    overflow: hidden;
}
</style>


and then passing different size options to modal window initialization ..

```
$('.nm1').nm({
    sizes: {
        minH: 500,
        minW: 650
    }
});

   $('.nm2').nm({
    sizes: {
        minH: 500,
        minW: 1050
    }
   });
```

**Comment by milnerm** [comment]
any real documentation would help...

**Comment by PandaWood** [comment]
So, just to get this straight, we've gone from specifying type: 'iframe', in 1.6 to having to hard code a width in my CSS in v2. Is there any argument why it is done this why?

**Comment by PandaWood** [comment]
I cannot even work out how to specify an iframe since the option type: 'iframe' was taken out.
