### ISSUE TITLE
$.nmTop() error after form.nyroModal submit

### ISSUE THREAD

**Issue by stfr** [nyroDev/nyroModal#71]
Hello,
If you submit a form with class='nyroModal' in order to post the form on the modal, we can't use $.nmTop() : 

TypeError: $.nmTop is not a function

**Comment by nyroDev** [comment]
Could you provide an example please.
As far as I know, it shouldn't be a problem.

**Comment by stfr** [comment]
You can see it here : http://stephanerouille.fr/labs/experiments/nyromodalv2/

**Comment by odan** [comment]
Hello, I have the same problem. 
How to solve it?

**Comment by stfr** [comment]
This issue was solved in the last version of nyromodal v2.

**Comment by odan** [comment]
Thank you

**Comment by couresel** [comment]
There is a similar scenario that happens with form enctype="multipart/form-data"

In fact, if you were to take the example cited in this thread and modify the form to include this property/attribute, the symptoms present themselves.
