### ISSUE TITLE
Previous button doesn't work

### ISSUE THREAD

**Issue by nemona** [nyroDev/nyroModal#73]
Hi!
I'm working with nyromodal jquery image gallery, and since the beginning the previous button doesn't work, and I don't know where the problem is. The example is http://www.nemona.es/nueva/print.html... some help?
Thanks! (and sorry for my English...)

**Comment by nyroDev** [comment]
I'm getting a 404 error page.

**Comment by nemona** [comment]
ok, it's without the dots at the end, the example is: http://www.nemona.es/nueva/print.html
Thanks!

**Comment by nyroDev** [comment]
You set the width of the link to 100% here:
.nyroModalImage .nyroModalPrev, .nyroModalImage .nyroModalNext {
    height: 100%;
    width: 100%;
    max-height: none;
}

Put it back to 40% as initial and it'll work.

**Comment by nemona** [comment]
Thanks! it works!!
