### ISSUE TITLE
resize: function(recalc) - example

### ISSUE THREAD

**Issue by ppaul129** [nyroDev/nyroModal#75]
I am having a hard time figuring out how to get the resize function to work properly. I am trying to add 200 pixels of width to the modal if there is an error in a form submission. Can you post an example of how I would call that function? I cannot find any decent examples anywhere. Just having a hard time adjusting to v2.

thank you for all the hard work!

-Pete

**Comment by nyroDev** [comment]
the resize function is here to recalculate the optimal size of the modal, and then actually resize it.
Calling it without any argument will simply replace it after a windows resize for instance.
Calling with true as the only argument will recalculate the internal modal size and reajust the modal size regarding that.

To call it, you can do:
$.nmTop().resize(true);

**Comment by ppaul129** [comment]
The main issue I am trying to solve is that we are using .net and need all our forms to be in iframes so that they post back correctly. If there is an error message, the modal does not change size, it just gets scroll bars. We have been fighting this issue for a while. We must be doing something wrong. Is there a way to have the modal change size based on what happens in the iframe? I tried firing a function when the form has validation errors, but I cannot get the modal to resize.
