### ISSUE TITLE
TypeError: $(".nyroModal").nyroModal is not a function

### ISSUE THREAD

**Issue by ivfiam** [nyroDev/nyroModal#78]
This is how my page look like:
&lt;html lang="en">

&lt;head>

&lt;link href="/css/nyroModal.css" type="text/css">

&lt;script type="text/javascript" src="http://code.jquery.com/jquery-1.4.4.js">&lt;/script>

&lt;script type="text/javascript" src="/js/jquery.nyroModal.custom.js">&lt;/script>

&lt;!--[if IE 6]>

```
<script type="text/javascript" src="/js/jquery.nyroModal-ie6.js"></script>
```

&lt;![endif]-->

&lt;script type="text/javascript">

```
$(function() {

    $('.nyroModal').nyroModal()});

</script>
```

&lt;/head>

&lt;body>
&lt;a href="/link/to/anypage/" class="nyroModal">this does not work&lt;/a>
&lt;/body>

I have downloaded  jquery.nyroModal.custom.js from http://nyromodal.nyrodev.com/create.php, by selecting all of the options.
All of the images, css and js files are in place.
The link is displayed as normal link, when clicking on it it opens content as any other link (no pop-up).
I have tried settings target="_blank", it does not work with that either.

I am always getting (when debugging java script) the same error (extract from stack trace): 

[e] message = [string] "$(\".nyroModal\").nyroModal is not a function"

Exception ``TypeError: $(".nyroModal").nyroModal is not a function'' thrown from function anonymous(wait=void:void) in 

&lt;http://code.jquery.com/jquery-1.4.4.js> line 447.

[e] message = [string] "$(\".nyroModal\").nyroModal is not a function"

Exception ``TypeError: $(".nyroModal").nyroModal is not a function'' thrown from function anonymous() in 

&lt;http://code.jquery.com/jquery-1.4.4.js> line 875.

Please help me

**Comment by nyroDev** [comment]
please, try by using jQuery 1.5.2 (or last version) first.

**Comment by ivfiam** [comment]
Thank for fast replay.
Same thing is with 1.5.2
Here is the stack trace:
[e] message = [string] "$(\".nyroModal\").nyroModal is not a function"

Exception ``TypeError: $(".nyroModal").nyroModal is not a function'' thrown from function anonymous(args=Array:{0}, context=HTMLDocument:{2}) in &lt;http://code.jquery.com/jquery-1.5.2.js> line 975.

[e] message = [string] "$(\".nyroModal\").nyroModal is not a function"

Exception ``TypeError: $(".nyroModal").nyroModal is not a function'' thrown from function anonymous(args=Array:{0}, context=HTMLDocument:{2}) in &lt;http://code.jquery.com/jquery-1.5.2.js> line 980.

[e] message = [string] "$(\".nyroModal\").nyroModal is not a function"

Exception ``TypeError: $(".nyroModal").nyroModal is not a function'' thrown from function anonymous(wait=void:void) in &lt;http://code.jquery.com/jquery-1.5.2.js> line 414.

[e] message = [string] "$(\".nyroModal\").nyroModal is not a function"

Exception ``TypeError: $(".nyroModal").nyroModal is not a function'' thrown from function anonymous() in 
&lt;http://code.jquery.com/jquery-1.5.2.js> line 881.

**Comment by nyroDev** [comment]
Weird. Is it possible for you to setup a test page somewhere?

**Comment by ivfiam** [comment]
Unfortunately not :-(

**Comment by ivfiam** [comment]
If it is of any help, 
I have found old nyroModal version 1.6.2 from http://code.google.com/p/nyromodal/downloads/detail?name=nyroModal-1.6.2.zip&can=2&q= 
and that one works 
Tu as raison, c'est étrange. 
Merci pour essayer de m'aider
