### ISSUE TITLE
how to change the min Height of the modal

### ISSUE THREAD

**Issue by toandph** [nyroDev/nyroModal#8]
I want to change the min Height to 150 of the modal of hidden div! but I try the following code it doesn't work.

options = { sizes : {initW: 700,    initH: 150, w: 700, h: 150, wMargin: 5, hMargin: 5} };
$('#loginLnk').nm(options);

**Comment by nyroDev** [comment]
Add sizes.minW and sizes.minH settings. Closed by ba819674fd1f3eb35983d1ebd7c9499e24808792
