### ISSUE TITLE
Moving the nyromodal window

### ISSUE THREAD

**Issue by nemona** [nyroDev/nyroModal#80]
Hi again,

I'm trying to move the javascript window, but always appears the scrolls. The window is fixed in the middle of the page and I can't move it anymore. I've been trying to change some parameters of the .js but if, at least the window is where I want, the .js doesn't work.

The example is here: http://www.nemona.es/nueva/print2.html

Thanks for all.
Elena.

**Comment by nyroDev** [comment]
Firstly, start by including the original CSS from nyroModal in order to get a working modal.

Then, I don't understand what you mean with "moving the window". Could you be more specific please?

**Comment by nemona** [comment]
Ok, I have included the original Nyromodal CSS. Now, in the example, if you click in "triptico IVI", you can see that the window is pisitioned in the middle of the screen. I want to place the window to the right, to fit it with my design square.
After, I'll put no background and no border.
I hope I have explained it well...

**Comment by nyroDev** [comment]
To do that, I'm not sure that a modal plugin is the best solution.
A modal solution is done to be over all elements on the page, not be juxtaposed with items on it.

The solution for you should be to develop by yourself what you need, by using some basic jQuery functions.
