### ISSUE TITLE
Cached images do have width = 0

### ISSUE THREAD

**Issue by nidefawl** [nyroDev/nyroModal#81]
When using $.nmManual('http://imageurl....'); and the image is already cached it does not resize the container,
it thinks the images width is zero. I was not able to build a workaround.

Tested on Chrome 10.0.648.205

**Comment by gekk00** [comment]
I'm having the same issue with the image modal.... in fact it seems that on the nyromodal website, if you click on the "image" link, then close it, and then reopen - same problem... seems to work in safari and firefox, seems to be just chrome that gets this error

**Comment by nyroDev** [comment]
Is this issue still occuring?

**Comment by gekk00** [comment]
Yea it's still an issue. I thought i'd posted my little work around... basically what i had to do in the end was right a bit of jquery that would modify the src tag of the image that you'd click with a random bit rubbish on the end like this:

$("img").click(function(){
        currentSrc = $(this).attr("src");
        appendage = Math.floor(Math.random()_10_10);
        $(this).attr("src",currentSrc + "?" + appendage);
        currentSrc = $(this).attr("src");
    });

this stopped it from caching and resolved the problem... but obviously its just a rough work around and not really ideal

**Comment by nyroDev** [comment]
Do you have a test page where I can see this issue?
I would like to check the header sent by the server.

**Comment by robot3498712** [comment]
Thanks very much gekk00 for posting your beautiful fix!
I've also had troubles getting the lightbox to work with chrome,
Below is my solution for rewriting img hrefs on the fly and restoring on close. Hope it's useful ...

---

```
jQuery('.nyroModal').nm({
    callbacks: {
    initElts: function(nm) {
        var href = nm.opener.attr('href');
        nm.opener.attr('href_default',href);
        var r = Math.floor(Math.random()*10*100000);
        nm.opener.attr("href",href + "?" + r);
    },
    afterClose: function(nm) {
        var href = nm.opener.attr('href_default');
        nm.opener.attr("href",href);
    }
    }
});
```

**Comment by stonys** [comment]
This fix doesn't work for me. After clicking few times on image i see image source code :)

like this: ..����G_�H������%��߶W��!����W�4����e��/����{�������?���J�撏�m��+���������+��J�~�˲���..

**Comment by stonys** [comment]
Update: this fix works fine, if you don't click next or previous buttons on the image.

**Comment by stonys** [comment]
Update 2: Makes not much sense, but when afterClose function is changed to filledContent it seems to work 

```
callbacks: {
            initElts: function(nm) {
                var href = nm.opener.attr('href');
                nm.opener.attr('href_default',href);
                var r = Math.floor(Math.random()*10*100000);
                nm.opener.attr("href",href + "?" + r);
            },
            filledContent: function(nm) {
                var href_def = nm.opener.attr('href_default');
                nm.opener.attr("href",href_def);
            }
        }
```

**Comment by nyroDev** [comment]
Your fix is basically to remove cache features for the images, which is not an acceptable solution to me.
Is this bug still occuring?
I testes on Chrome 22 and everything seems OK to me.

**Comment by nyroDev** [comment]
Is it still occuring?
