### ISSUE TITLE
NyroModal Problem using JQuery UI Accordion

### ISSUE THREAD

**Issue by tonsn** [nyroDev/nyroModal#82]
Hello!

This ist my Code:

<pre>
  &lt;script type="text/javascript" src="http://code.jquery.com/jquery-latest.pack.js"></script>
  &lt;script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>
  &lt;script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>
  &lt;script type="text/javascript" src="assets/js/jquery.nyroModal/js/jquery.nyroModal.custom.js"></script>
</pre>

at the end of the doc:

<pre>
  &lt;script>
  jQuery(document).ready(function(){
    jQuery( '#accordion' ).accordion({ header: '.criteria' });
    jQuery( '#accordion' ).accordion({ collapsible: true });
    jQuery( '#accordion' ).accordion({ active: false });
    jQuery('.nyroModal').nyroModal(); 
  });
  &lt;/script>
</pre>

The accordion works fine, but when i click on a modal it just opens an overlay size of a stamp and no content. Firebug says:
Node cannot be inserted at the specified point in the hierarchy" code: "3

Before i combined NyroModal with Accordionit worked just fine. I'd love to keep it. Ideas?

Thank you all very much!

tonsn

**Comment by nyroDev** [comment]
Firstable, why do you include 2 times jQuery library?

Then, the rest of your HTML page might help to understand what's going on.
What could be even better is a demo page of your bug, hosted somewhere...

**Comment by tonsn** [comment]
Oh. Good point. I keep the latest Pack link. It seems the problem only occurs when testing it local - after i loaded it  via ftp on the server evrything worked fine. so sorry for stealing your precious time. thnak you very, very much.

**Comment by nyroDev** [comment]
ok, thanks for letting me know and closing the bug
