### ISSUE TITLE
creating a link in title=

### ISSUE THREAD

**Issue by chard** [nyroDev/nyroModal#83]
Hi
how do i add link to the title=?
from the previous version i just use this method
title=
      "sample &lt;A HREF=&quot;link.html&quot;
but this doesnt work with the latest?

**Comment by nyroDev** [comment]
I answered with a blog post here: http://nyrodev.info/en/posts/267/nyroModal_create_a_link_in_the_title

In 2 words:
Add a rev attribute to the opener link containing the URL of where you want the link.

Add nyroModal behavior with:
    jQuery(function($) {
        $('.nyroModal').nm({
            callbacks: {
                beforeShowCont: function(nm) {
                    if (nm._hasFilter('title') && nm.opener.is('[rev]')) {
                        nm.store.title.html('<a href="'+nm.opener.attr('rev')+'">'+nm.store.title.text()+'</a>');
                    }
                }
            }
        });
    });

**Comment by chard** [comment]
wow! Thanks a lot!
