### ISSUE TITLE
$.nmTop().resize() in second modal doesn´t work

### ISSUE THREAD

**Issue by epsaturn** [nyroDev/nyroModal#85]
There are 5 Forms in a row, called as modals. Sometimes content is loaded via Ajax and then the modal should resize.
The method works fine in first Modal, then another Modal is loaded from a link in this first Modal.
That second modals content is changed via Ajax. After the loading the resize()-method is called again.
I will get this error (using firebug): $.nmTop() is undefined

the resize-method is called in this way:

```
$('.ownsDomain').live('click',function(){
    var url2check = $('#url2check').val();
    var script = 'url';
    $('.result').load(script, function(){$.nmTop().resize(true);})
});
```

**Comment by nyroDev** [comment]
Is this bug still occuring wis the current release?

**Comment by bgcena** [comment]
Hi i am getting the same error 

$.nmTop().close();

Uncaught TypeError: Cannot read property 'close' of undefined
