### ISSUE TITLE
Client side form validation in modal calling modal

### ISSUE THREAD

**Issue by paulpersys** [nyroDev/nyroModal#86]
I have a series of nyromodal windows with forms which work fine   - however I would like to add very basic client side field validation to 3 text fields on the first modal - to verify content/well formed email - before submitting to the second modal.
Ideally using the validate plugin. I have tried numerous methods including some of the solutions already posted here but have only succeded in breaking it!  The link below points to an example of the modals in use without any validation for the name & email fields  

 http://www.persys.me.uk/shoot.asp?shootid=7

click on the Order/Download button to trigger first modal

Any help/strategies as to how to implement validation would be great - I'm sure it is straight forward I'm just not getting it at the moment

**Comment by paulpersys** [comment]
Sorry didn't include modal code extract
...

<pre><code>
$(document).ready(function() {

 /*var validForm = $('#detailsForm').submit(function(e) {
      e.preventDefault(); 
   $(':text').each(function() {
    if ($(this).val().length == 0){
      $(this).css('border', '1px solid red');
    } else {
      e.preventDefault(); 
      validForm.nyroModal().nmCall();
      return false;  
    }
    });
  });
$('#selectionForm').validate({
    submitHandler: function(form) {
        $(form).nyroModalManual();
    }
});
*/
$('#selectionForm').validate({
                rules: {
                    fname: {
                    required: true
                    },
                    lname: {
                    required: true
                    },
                    email: {
                    required: true
                    }
                },

```
submitHandler: function(form) {

    $('#selectionForm').submit(function(e) {
        e.preventDefault();
            $(this).nyroModal().nmCall();
        return false;
    });
        $.nyroModalSettings({
                minWidth: 600, // Minimum width
                minHeight: 500 // Minimum height
        });
```

});
});
});
</script>
</code></pre>....

**Comment by nyroDev** [comment]
You have different solution to execute javascript on a modal.
The one I prefer is simply to include a script tag on the loaded ajax page.

An other idea might be to use one of the multiple callback using the nm object to detect if the loaded page is the form.
