### ISSUE TITLE
nyroModal options issue

### ISSUE THREAD

**Issue by andretxu** [nyroDev/nyroModal#87]
Hi,
i am not a web designer, just an italian writer creating is web site all by himself so sorry for but poor english and for very low level problem.

I am using DOM element hidden div  nyroModal effect and it s working nicely but clicking on the background the modal is closed instead of the buttonClose, that is i want close the modal effect only by the correct button and not everywhere on the background. I have seen there isthe following option about it:

closeOnClick: true, // Indicates if a click on the background should close the modal

but it s not working cz i do some mistake for sure but dont know where i am wrong:-( here it s the test code i am trying to work:

<pre>
&lt;!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
&lt;html>
&lt;head>
&lt;link rel="stylesheet" href="nyroModal.css" type="text/css" media="screen" />

&lt;head>
&lt;script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js">&lt;/script>
&lt;script type="text/javascript" src="jquery.nyroModal.custom.js">&lt;/script>
&lt;script type="text/javascript" src="jquery.nyroModal-ie6.min.js">&lt;/script>
&lt;/head>

&lt;body>
&lt;a href="#test" class="nyroModal">DOM Element (hidden div)&lt;/a>
&lt;div id="test" style="display: none; width: 600px;">Open a new modal&lt;br />Test
&lt;a href="#" class="nyroModalClose nyroModalCloseButton nmReposition" title="close">Close&lt;/a>
&lt;/div>
    
&lt;script type="text/javascript">
$(function() {
  $('.nyroModal').nyroModal();
  $.nmObj({closeOnClick:'false'}); 
});
&lt;/script>
&lt;/body>
&lt;/html>
</pre>

any help? thx a lot.-)

andrea

**Comment by nyroDev** [comment]
Regarding your source:
Don't include the ie6 script for all browser, but only for IE6 as explained here: http://nyromodal.nyrodev.com/#usage
You also have 2 &lt;head> tags...

Then, regarding your specific problem, do your code like:
  $('.nyroModal').nyroModal({closeOnClick:'false'});

And it will work.

**Comment by andretxu** [comment]
hi nyro thx for ur replay, 
i did as u wrote but does not work yet. the only way to does work is change the option directly in the query.nyroModal.custom.js code without put {closeOnClick:'false'} in the html code.
i mean put it 'false' in the js code and not in the latter as it should be...that sounds strange also for me but ...i dont know...
