### ISSUE TITLE
How to use ajax post value?

### ISSUE THREAD

**Issue by cj333** [nyroDev/nyroModal#88]
Hi, thanks for a nice script. But can I post value to a modal box page?
I have read all your articles and searched from google. Just find one article. http://code.google.com/p/nyromodal/issues/detail?id=121

but not work for me.

here is my code, I import 2 of your js files. where is the problem? Thanks and regards.

index.php

<pre>[link rel="stylesheet" href="nyroModal.css" type="text/css" media="screen" />
[script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js"></script>
[script type="text/javascript" src="js/jquery.nyroModal.js"></script>
[script type="text/javascript" src="js/jquery.nyroModal.filters.link.js"></script>
[!--[if IE 6]>
  [script type="text/javascript" src="jquery.nyroModal-ie6.js"></script>
[![endif]-->
[script type="text/javascript"> 
jQuery(document).ready(function(){
$(".nyroModal").click(function(){
  var value = $(this).attr('title');
  var modalUrl = 'u2.php?color=' + value;
$.ajax({
   url: "u2.php", 
   dataType: "html",
   type: 'POST', 
   data: "color="+value, 
   success: function(data){   
      $.nmFilters({  
          url: modalUrl,
          closeButton: true             
      });   
   }
   });
});
});
[/script>
[a href="javascript:void(0)" class="nyroModal" title="red">Red[/a><br />
[a href="javascript:void(0)" class="nyroModal" title="blue">Blue[/a><br /></pre>

u2.php

<?php echo 'this color is'.$_POST['color']; ?>

ie and firefox have no wrong alart, but can not return a pop box.

**Comment by nyroDev** [comment]
First, use also the data filter.
Then, on your success ajax function, try:

<pre>$.nmData(data);</pre>
