### ISSUE TITLE
nyroModal version system

### ISSUE THREAD

**Issue by soloincc** [nyroDev/nyroModal#89]
Which versioning criteria does nyroModal use? On the downloads page, http://nyromodal.nyrodev.com/create.php?dl=1, on nyroModal home page, a custom version is available for download, yet I didn't specify a custom download. I have no way in knowing which version I am using! A proposal to have all releases have a version if this is not being implemented!

**Comment by nyroDev** [comment]
Ok, I'll found a way to include the github commit number in the js files generated.
Thansk for your proposal

**Comment by nyroDev** [comment]
The commit number and date are now add in the comment of js files.

**Comment by soloincc** [comment]
Good to know this is addressed
