### ISSUE TITLE
IFrame with Custom Size

### ISSUE THREAD

**Issue by ghost** [nyroDev/nyroModal#90]
Hello,
I don´t understand how can  i call an iframe with custom Modal size.
I have tried al lot of different ways, but they don´t works.

$(".nyroModal").nyroModal(size:{w:1024,h:800});

I don´t find an example in the documentation and all other issues that reffers here for the same problem, doesn´t works for me.

Can somebody help me?

Thanx.

**Comment by nyroDev** [comment]
You have to change the CSS in order to modify the default size.
