### ISSUE TITLE
Cannot Set Width of Dialog

### ISSUE THREAD

**Issue by wat5** [nyroDev/nyroModal#91]
I am trying to set the width of a dialog but it will not take.   I am sure I am doing this wrong.

$.nmManual('/url',{sizes: { initW: 300, initH: 300,w: 300, h: 300 }});

The content is HTML 5 based content loaded via ajax.   Do I have to set a width to the page or something?

Thanks - C

**Comment by jkorff** [comment]
I'm having the same issue:

```
        $('.carousel ol li > a').nyroModal({
            galleryCounts: false,
            useKeyHandler: true,
            sizes: {
                initW: 604,
                initH: 362,
                w: 604,
                h: 362,
                minW: 604,
                minH: 362
            },
```

[....]

Is there any solution?

**Comment by halwaxt** [comment]
Have you tried $.nmTop().resize(true); in your ajax.success function?

**Comment by jkorff** [comment]
Where would I need to insert that code? I'm not using Ajax to pull in content.

**Comment by halwaxt** [comment]
Try to call it in some of the callbacks. Maybe afterReposition is the right one.

 $(this).nyroModal({
            callbacks: {
                afterReposition: function (nm) {
                 $.nmTop().resize();
                }
            }

**Comment by jkorff** [comment]
Ok, I will try at work tomorrow (where I use nyroModal for a project). Thank you for your suggestion.

**Comment by jkorff** [comment]
Hm, that doesn't work for my setup. When I add this the popup opens as usual, but clicking on previous or next just gives me a blank popup area. Commenting out the "resize" line fixes it.

**Comment by nyroDev** [comment]
You have to use CSS in order to change the default size of modals.

**Comment by halwaxt** [comment]
Danke fr Ihre Nachricht. Ich bin ab dem 21.9.2011 wieder erreichbar. Ihre E-Mails werden nicht weitergeleitet. In dringenden Fllen wenden Sie sich bitte an Hrn. Michael Blaha: Michael.Blaha@iktopia.at oder 0664/8546961.
