### ISSUE TITLE
Compatibility with AdSense

### ISSUE THREAD

**Issue by PLMCHL** [nyroDev/nyroModal#92]
When I try to load some javascript code to show an ad from google adsense, such as:

``` javascript
<script type="text/javascript" ><!--
google_ad_client = "***";
google_ad_slot = "***";
google_ad_width = 468;
google_ad_height = 60;
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
```

It is not possible to see it in the modal box. After adding rel="forceLoad" and rev="shown" to the second script tag, it still does not work and the forceload makes my page go blank as it tries to load something.

Is there a way to show adds from adsense inside nyromodal?

**Comment by nyroDev** [comment]
The problem with adsense is that it use the document.write instruction to show it's ads on the place where the script is loaded.

nyroModal doesn't include js element on the exact place where they are included at the begginning.

To solve your problem, you might do something like:
- Replace your adSense code with a retrivable DOM element (<span class="adsense"></span>)
- Use a nyroModak callback to replace these span with your adsense code with jQuery.

NB : I'm not sure if jQuery will load the js file in the place where you try to load it. I'm sure there is some solution around it to do it with jQuery.
