### ISSUE TITLE
Form data should stay

### ISSUE THREAD

**Issue by mSignore** [nyroDev/nyroModal#93]
Hello.
Thank you for your best script.
I've a question:
I've a form. It has some inputs and a textarea. My form is in an external file, and I want to show it with nyroModal.
But I have problem. When I open it in Ajax mode, and write some text in the inputs; if I close it and reopen the modal, my previous data disappeared and all the inputs are empty.
How can I open and close the modal that the form data will stay?

I thought about it and realized that after clicking on "close" link, the temporary div (that nM place the ajax response text in it) doesn't remove and take a "display: none" style; and when I reopen it, that invisible div shows (and don't go and get the source again with ajax), my problem can be solved.

But how?????

Thank you very much (mercy).
[sorry for my bad English]

**Comment by nyroDev** [comment]
Using display: none should bot be the solution.

Instead, you could do something like:
1) Using beforeHideCont callback to save the form data in a local variable
2) Using beforeShowCont callback to put the data back in the form, if the local variable is filled
