### ISSUE TITLE
Next and Prev Tabs static

### ISSUE THREAD

**Issue by jessehampton** [nyroDev/nyroModal#94]
I'm wondering how I can make the next and previous tabs always visible (so it work's better on an ipad)

Currently, they are only active on hover. Is there anyway to make them static, always visible?

Thanks so much!

**Comment by mindbodyheart09** [comment]
You can modify nyroModal.css to the effect desirable.

**Comment by nyroDev** [comment]
As said mindbodyheart09, you simply have to update the CSS to fit your needs.
