### ISSUE TITLE
nyroModal with jQuery 1.6 closebutton stuck in Chrome

### ISSUE THREAD

**Issue by kyllle** [nyroDev/nyroModal#95]
When I open nyroModal in Chrome and resize the window the closeButton fails to reposition to the new dimensions instead remaining fixed to its original position. I have tested this problem and found that it is being caused by jquery 1.6

**Comment by conancat** [comment]
I am getting this problem too. Apparently in Firefox if you do a setTimeout before resizing the window it will be okay, but it still gets stuck in Chrome. Need to debug this individually to find out what's causing the problem I think. :(

**Comment by nyroDev** [comment]
Is this problem still ocurring?

**Comment by PalleZingmark** [comment]
I get this problem with Safari, both Mac and iPad.
Any suggestions?

**Comment by conancat** [comment]
after playing around a bit I think it only appears if you're using `$.nmData()`. the `.nyromodal()` bindings seem to works fine, so my personal way of going around it is to create an empty and hidden container somewhere on the page, have a hidden trigger on the page, binding that trigger with `.nyromodal()`, then add in the contents to the container before calling the `$('.lightbox-trigger').trigger('click')`. 

but i hope it does get fixed soon though... :(

**Comment by nyroDev** [comment]
This issue doesn't seem to exist anymore.
