### ISSUE TITLE
v1.6 endRemove vs 2.0 afterClose

### ISSUE THREAD

**Issue by sevl** [nyroDev/nyroModal#97]
Hello,

i hope this is the right place to ask this question. before 2.0 the endRemove - callback had the settings parameter which among other stuff provided the url of the link, which was opened in the modal. Is there any way to get this information in the afterClose-Callback?

best regards
Severin

**Comment by nyroDev** [comment]
yes, you can use the nm object (provided as the first setting of this callback) and the opener paramater of this object.

nm.opener is the jQuery element that opened the modal (like your <a> or <form> for instance)
You can then do your stuff with this element.

If you want to retrieved directly the URL used to load, you can do something like:

<pre>var url = nm._hasFilter('link') ? nm.store.link.url : nm.store.form.url;</pre>


Hope it helped.
