### ISSUE TITLE
modal title

### ISSUE THREAD

**Issue by pjam** [nyroDev/nyroModal#99]
Hi!

I'm trying to make a title have the same width as the modal. I managed to do what I want by changing the title filter in line 1009-1013 like this:

``` javascript
beforeShowCont: function(nm) {
                var offset = nm.elts.cont.offset();
                nm.store.title = $('<h1 />', {
                    text: nm.opener.attr('title')
                }).addClass('nyroModalTitle nmReposition').css('width', nm.elts.cont.css('width'));
```

The problem I have is when the modal resizes... the title gets as large as the text, like it was without my change.

How can I solve this to work as I want?

**Comment by nyroDev** [comment]
You can use the afterResize callback with the exact same function than your beforeShowCont callback.
